<?php
/**
 * Lyonscg_RequisitionList
 *
 * @category  Lyons
 * @package   Lyonscg_RequisitionList
 * @author    Tetiana Mamchik<tanya.mamchik@capgemini.com>
 * @copyright Copyright (c) 2020 Lyons Consulting Group (www.lyonscg.com)
 */

/**
 * @var $block \Magento\RequisitionList\Block\Requisition\View\Details
 */
?>
<div class="remove__wrap-mass">
<!-- ko scope: 'remove_items_massaction' -->
<button type="button"
        title="<?= $block->escapeHtmlAttr(__('Remove Selected')) ?>"
        data-mobile-label="<?= $block->escapeHtmlAttr(__('Remove')) ?>"
        class="action remove-selected"
        data-bind="click: applyAction.bind($data, {
            requisition_id: '<?= (int) $block->getRequest()->getParam('requisition_id') ?>'
        })">
    <span><?= $block->escapeHtml(__('Remove Selected')) ?></span>
</button>

<!-- /ko -->
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "remove_items_massaction": {
                        "component": "Magento_RequisitionList/js/requisition/items/grid/massaction",
                        "selectProvider": "requisition.item.grid.selection.provider",
                        "hasConfirm": true,
                        "confirmConfig": {
                            "title": "Remove from Quote?",
                            "content": "Are you sure you would like to remove selected items from the quote?",
                            "modalClass": "requisition-popup modal-slide",
                            "confirmLabel": "<?= $block->escapeJs(__('Delete')) ?>"
                        },
                        "action": "<?= $block->escapeUrl($block->getUrl('requisition_list/item/delete')) ?>"
                    }
                }
            }
        }
    }
</script>
</div>
