<div class="inspirations-dropdown">
    <span class="action toggle"
          data-toggle="dropdown"
          aria-haspopup="true"
          data-mage-init='{"dropdown":{}}'>
        <span>Ideas & Inspiration</span>
     </span>
    <ul class="dropdown" data-target="dropdown">
        <?php // content filled here by JS in circa.js to move Ideas and Inspirations category <li>s here ?>
    </ul>
</div>
