<?php
/**@var  \Capgemini\PaperModel\Block\Widget\PaperModelButtons $block */
?>
<div class="paper-mode-buttons-wrapper" id="paper-mode-buttons-wrapper">
    <?php if ($block->isPaperModelSalable()): ?>
        <div class="paper-model-button add-to-cart">
            <button type="submit" title="Add paper template to cart" class="action primary tocart" id="product-addtocart-button-paper-model">
                <span><?= __('Add paper template to cart'); ?></span>
            </button>
        </div>
    <?php endif; ?>
    <div class="paper-model-preview">
        <a id="paper-model-preview-button" target="_blank" class="action primary paper-model-preview-button" href="#"><?= __('Preview paper template'); ?></a>
    </div>
</div>
