<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php $partnersInsightHelper = $this->helper(\Capgemini\PartnersInsight\Helper\Invoice::class) ?>
<?php $poNumber = $partnersInsightHelper->getPoNumber() ?? ''; ?>
<?php $status = $partnersInsightHelper->getStatus() ?? ''; ?>
<?php $dueDate = $partnersInsightHelper->getDueDate() ?? ''; ?>
<div class="project-data">
    <div class="invoice-col-1">
        <?php if($poNumber) { ?>
        <div>
            <strong class="label">Purchase Order #: </strong>
            <span><?= $poNumber ?></span>
        </div>
        <?php } ?>
        <?php if($dueDate) { ?>
            <div>
                <strong class="label">Invoice Due Date: </strong>
                <span><?php echo $dueDate ?></span>
            </div>
        <?php } ?>
    </div>
    <div class="invoice-col-2">
        <div class="order-date">
            <strong class="label">Invoice Date: </strong>
            <span><?php echo $partnersInsightHelper->getInvoiceDate() ?></span>
        </div>
        <?php if($status) { ?>
            <div>
                <strong class="label">Status: </strong>
                <span><?= $status ?></span>
            </div>
        <?php } ?>
    </div>
</div>
