<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
use Magento\Customer\Block\Widget\Gender;
use Magento\Customer\Block\Widget\Name;
use Magento\Directory\Helper\Data; ?>
<?php
/**
 * Create account form template
 *
 * @var $block \Capgemini\Company\Block\Company\Account\Create
 */
?>
<?php
    /** @var \Lyonscg\CircaLighting\ViewModel\WebsiteSwitcher $storeResolver */
    $storeResolver = $block->getData('store_resolver');
    $storeDataUsedInTemplate = $storeResolver ? $storeResolver->getStoreDataUsedInTemplate() : [];
    $currentStoreCode = $storeResolver->getCurrentStoreCode();
    $storeCode = $storeDataUsedInTemplate[$currentStoreCode]['uppercase'] ?? '';
?>
<form class="form create account form-create-account"
      action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
      method="post" id="form-validate"
      enctype="multipart/form-data"
      autocomplete="off">
    <div class="field note no-label">
        <strong><?= $block->escapeHtml(__('Enjoy great benefits with our Trade Program')) ?></strong>
        <p>Interior designers, architects, builders and other design professionals are invited to join our Trade Program.</p>
        <div class="wrapper icons">
            <div class="column-50">
                <div class="icon tag">Exclusive trade pricing on every order-no purchase minimum</div>
                <div class="icon gear">Easily generate quotes, place and track orders online</div>
                <div class="icon documents">Generate tear sheets with pricing removed for client presentation</div>
            </div>
            <div class="column-50 right">
                <div class="icon cad">Download CAD block drawings of our products</div>
                <div class="icon people">Courtesy in-store and on-site consultations to clients within range of one of our 20+ showrooms across the country</div>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="notice">
            <?= $block->getChildHtml('top_notice'); ?>
        </div>
    </div>
    <?= $block->getBlockHtml('formkey') ?>
    <fieldset class="fieldset info">
        <legend class="legend"><span><?= $block->escapeHtml(__('Company Information')) ?></span></legend>
        <?= $block->getLayout()->createBlock(Name::class)
            ->setFieldNameFormat('customer[%s]')
            ->setObject($block->getFormData())
            ->setNoWrap(true)
            ->setForceUseCustomerAttributes(true)
            ->toHtml() ?>
        <div class="field company-name _required">
            <label class="label" for="company_name">
                <span><?= $block->escapeHtml(__('Company Name')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="company[company_name]" id="company_name"
                       value=""
                       title="<?= $block->escapeHtmlAttr(__('Company Name')) ?>"
                       class="input-text" data-validate="{required:true}">
            </div>
        </div>
        <div class="field website">
            <label class="label" for="website">
                <span><?= $block->escapeHtml(__('Company Website')) ?> <span>(Optional)</span></span>
            </label>
            <div class="control">
                <input type="text" name="company[website]" id="website"
                       value=""
                       title="<?= $block->escapeHtmlAttr(__('Company Website')) ?>"
                       class="input-text">
            </div>
        </div>
        <div class="field company-email _required">
            <label class="label" for="company_email">
                <span><?= $block->escapeHtml(__('Company Email')) ?></span>
            </label>
            <div class="control">
                <input type="email" name="company[company_email]" id="company_email"
                       value=""
                       title="<?= $block->escapeHtmlAttr(__('Company Email')) ?>"
                       class="input-text"
                       data-role="email"
                       data-async-is-valid="true"
                       data-mage-init='{"Magento_Company/js/form/element/async-validation": {
                            "name": "company_email",
                            "validateUrl": "<?= $block->escapeUrl($block->getUrl('company/account/validate')) ?>"
                       }}'
                       data-validate="{required:true, 'validate-email': true, 'validate-async-company-email': true}">
            </div>
        </div>
        <div class="field street _required">
            <label class="label" for="street0">
                <span><?= $block->escapeHtml(__('Address Line 1')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="company[street][0]" id="street0"
                       value=""
                       title="<?= $block->escapeHtmlAttr(__('Address Line 1')) ?>"
                       class="input-text" data-validate="{required:true}">
            </div>
        </div>
        <div class="field street">
            <label class="label" for="street1">
                <span><?= $block->escapeHtml(__('Address Line 2')) ?> <span>(Optional)</span></span>
            </label>
            <div class="control">
                <input type="text" name="company[street][1]" id="street1"
                       value=""
                       title="<?= $block->escapeHtmlAttr(__('Street Address')) ?>"
                       class="input-text">
            </div>
        </div>
        <div class="field city _required">
            <label class="label" for="city">
                <span><?= $block->escapeHtml(__('City')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="company[city]" id="city"
                       value=""
                       title="<?= $block->escapeHtmlAttr(__('City')) ?>"
                       class="input-text" data-validate="{required:true}">
            </div>
        </div>
        <div class="wrapper fields">
            <div class="field region-id required">
                <label class="label" for="region_id">
                    <span><?= $block->escapeHtml(__('State')) ?></span>
                </label>
                <div class="control _required">
                    <?php $message = $block->escapeHtml(__('- Select State')) ?>
                    <select name="company[region_id]" id="region_id" data-validate="{required:true}" class="select">
                        <option value=""><?= /* @noEscape */ $message ?></option>
                    </select>
                    <input type="text" id="region" name="company[region]"
                           value=""
                           title="<?= $block->escapeHtmlAttr(__('State')) ?>"
                           class="input-text" style="display: none;">
                </div>
            </div>
            <div class="field postcode required">
                <label class="label" for="postcode">
                    <span><?= $block->escapeHtml(__('ZIP/Postal Code')) ?></span>
                </label>
                <div class="control">
                    <?php $postcodeClass = $block->escapeHtmlAttr($block->getAttributeValidationClass('postcode')) ?>
                    <input type="text" name="company[postcode]" id="postcode"
                           value=""
                           title="<?= $block->escapeHtmlAttr(__('ZIP/Postal Code')) ?>"
                           class="input-text validate-zip-international <?= /* @noEscape */ $postcodeClass ?>"
                           data-validate="{'required':true, 'validate-zip-international':true}" />
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="field country_id _required">
            <label class="label" for="country_id">
                <span><?= $block->escapeHtml(__('Country')) ?></span>
            </label>
            <div class="control _required">
                <?php $countryValue = $block->getDefaultCountryId(); ?>
                <select name="company[country_id]" id="country_id"
                        class="select"
                        title="<?= $block->escapeHtmlAttr(__('Country')) ?>"
                        data-validate="{required:true}">
                    <option value=""></option>
                    <?php $countries = $block->getCountriesList(); ?>
                    <?php foreach ($countries as $countryCode => $country): ?>
                        <option value="<?= $block->escapeHtmlAttr($countryCode) ?>"
                            <?= ($countryCode == $countryValue) ? ' selected' : '' ;?>>
                            <?= $block->escapeHtml($country) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div class="field telephone _required">
            <label class="label" for="telephone">
                <span><?= $block->escapeHtml(__('Office Phone')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="company[telephone]" id="telephone"
                       value=""
                       title="<?= $block->escapeHtmlAttr(__('Office Phone')) ?>"
                       class="input-text" data-validate="{'required':true, 'company-telephone':true}">
            </div>
        </div>
        <div class="field cell_phone">
            <label class="label" for="cell_phone">
                <span><?= $block->escapeHtml(__('Cell Phone')) ?> <span>(Optional)</span></span>
            </label>
            <div class="control">
                <input type="text" name="company[cell_phone]" id="cell_phone"
                       value=""
                       title="<?= $block->escapeHtmlAttr(__('Cell Phone')) ?>"
                       class="input-text"
                       data-validate="{'validate-phoneStrict':true}">
            </div>
        </div>
        <div class="field fax">
            <label class="label" for="fax">
                <span><?= $block->escapeHtml(__('Fax')) ?> <span>(Optional)</span></span>
            </label>
            <div class="control">
                <input type="text" name="company[fax]" id="fax"
                       value=""
                       title="<?= $block->escapeHtmlAttr(__('Fax')) ?>"
                       class="input-text">
            </div>
        </div>
        <div class="field business_type _required">
            <label class="label" for="business_type_group">
                <span><?= $block->escapeHtml(__('Business Type')) ?></span>
            </label>
            <div class="control" id="business_type_group">
                <?php $idx = 0; ?>
                <?php foreach ($block->getBusinessTypes() as $value => $label): ?>
                    <input type="radio" name="company[business_type]" id="business_type_<?= $idx ?>"
                           value="<?= $block->escapeHtmlAttr($value) ?>">
                    <label for="business_type_<?= $idx ?>"><?= $block->escapeHtml($label) ?></label>
                    <?php $idx++; ?>
                <?php endforeach; ?>

                <input type="radio" name="company[business_type]" id="business_type_other"
                       value="other">
                <label for="business_type_other"><?= $block->escapeHtml(__('Other')) ?></label>
                <label class="label" for="business_type_other_value">
                    <span><?= $block->escapeHtml(__('Please specify')) ?></span>
                </label>
                <div class="control business-type-other">
                    <input type="text" name="company[business_type_other]" id="business_type_other_value"
                           value=""
                           title="<?= $block->escapeHtmlAttr(__('Please specify')) ?>"
                           class="input-text">
                </div>
            </div>
        </div>
        <?php if($block->getHelper()->isVatNumberEnabled()) : ?>
            <div class="field vat_number">
                <label class="label" for="vat_number">
                    <span><?= $block->escapeHtml(__('VAT number')) ?> <span>(Optional)</span></span>
                </label>
                <div class="control">
                    <input type="text" name="company[vat_number]" id="vat_number"
                           value=""
                           title="<?= $block->escapeHtmlAttr(__('VAT number')) ?>"
                           class="input-text">
                </div>
            </div>
        <?php endif; ?>
        <?php if($block->getHelper()->isMemberStateEnabled()) : ?>
            <div class="field member_state">
                <label class="label" for="member_state">
                    <span><?= $block->escapeHtml(__('VAT Member State')) ?> <span>(Optional)</span></span>
                </label>
                <div class="control">
                    <select type="text" name="company[member_state]" id="member_state"
                            value=""
                            title="<?= $block->escapeHtmlAttr(__('VAT Member State')) ?>"
                            class="select">
                        <?php foreach ($block->getMemberStateOptions() as $option): ?>
                            <option value="<?= $option['value'] ?>"><?= $option['label'] ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
        <?php endif; ?>
    </fieldset>
    <?php if (!$block->isCustomerLoggedIn()) : ?>
        <fieldset class="fieldset create info">
            <legend class="legend"><span><?= $block->escapeHtml(__('Sign-in Information')) ?></span></legend><br>

            <div class="field required">
                <label for="email_address" class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                <div class="control">
                    <input type="email" name="customer[email]"
                           autocomplete="email"
                           id="email_address"
                           value=""
                           title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                           class="input-text"
                           data-async-is-valid="true"
                           data-mage-init='{"Magento_Company/js/form/element/async-validation": {
                                "name": "customer_email",
                                "validateUrl": "<?= $block->escapeUrl($block->getUrl('company/account/validate')) ?>"
                           }}'
                           data-validate="{required:true, 'validate-email':true, 'validate-async-customer-email': true}">
                </div>
            </div>

            <?php if ($block->isNewsletterEnabled()) : ?>
                <div class="field choice newsletter">
                    <input type="checkbox" name="is_subscribed" title="<?= $block->escapeHtmlAttr(__('Sign Up For Circa Communications')) ?>" value="1" id="is_subscribed"<?php if ($block->getFormData()->getIsSubscribed()) :
                        ?> checked="checked"<?php endif; ?> class="checkbox"/>
                    <label for="is_subscribed" class="label"><span><?= $block->escapeHtml(__('Sign Up For Circa Communications')) ?></span></label>
                </div>
            <?php endif ?>

            <div class="field password required">
                <label for="password" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                <div class="control">
                    <input type="password" name="password" id="password"
                           title="<?= $block->escapeHtmlAttr(__('Password')) ?>"
                           class="input-text"
                           data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                           data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                           data-validate="{required:true, 'validate-customer-password':true}"
                           autocomplete="off">
                    <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                        <div id="password-strength-meter" class="password-strength-meter">
                            <?= $block->escapeHtml(__('Password Strength')) ?>:
                            <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                                <?= $block->escapeHtml(__('No Password')) ?>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="field confirmation required">
                <label for="password-confirmation" class="label"><span><?= $block->escapeHtml(__('Confirm Password')) ?></span></label>
                <div class="control">
                    <input type="password" name="password_confirmation" title="<?= $block->escapeHtmlAttr(__('Confirm Password')) ?>" id="password-confirmation" class="input-text" data-validate="{required:true, equalTo:'#password'}"/>
                </div>
            </div>
            <?php $userDefinedAttributes = $block->getLayout()->getBlock('customer_form_user_attributes'); ?>
            <?php if ($userDefinedAttributes): ?>
                <?php $userDefinedAttributes->setFieldNameFormat('customer[%1$s]'); ?>
                <?= $userDefinedAttributes->toHtml() ?>
            <?php endif; ?>

            <?= $block->getChildHtml('form.additional.info') ?>
        </fieldset>
    <?php endif ?>
    <fieldset class="fieldset create info">
        <legend class="legend"><span><?= $block->escapeHtml(__('Documentation')) ?></span></legend><br>
        <div class="admin__field-control admin__control-grouped">
            <?= $block->getChildHtml('bottom_notice'); ?>
            <input type="hidden" name="company[proof]" id="proof_of_trade" value=""/>
            <input type="hidden" name="company[tax-exempt]" id="tax_exempt" value=""/>
            <div id="company-documents" class="admin__field company-documents" data-bind="scope:'companyDocuments'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
        </div>
    </fieldset>

    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>">
                <span><?= $block->escapeHtml(__('Submit Account Request')) ?></span>
            </button>
        </div>
    </div>

</form>
<script>
    require([
        'jquery',
        'uiRegistry',
        'mage/mage'
    ], function($, registry) {

        var dataForm = $('#form-validate');
        var ignore = null;

        dataForm.mage('validation', {
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
        }).find('input:text').attr('autocomplete', 'off');

        $('#form-validate .action.save').on('click', function(){
            if ($(dataForm).valid()) {
                try {
                    $('#proof_of_trade').val(JSON.stringify(registry.get('companyDocuments.company-documents-fieldset.proofOfTrade').value()));
                    $('#tax_exempt').val(JSON.stringify(registry.get('companyDocuments.company-documents-fieldset.taxExempt').value()));
                } catch (err) {
                    console.log(err.message);
                }
                $('body').trigger('processStart');
            } else {
                $('body').trigger('processStop');
            }
        });
    });

    require([
        'jquery',
        'underscore',
        'jquery/file-uploader',
    ], function($, _) {

    });
</script>
<?php $countries = $this->helper(Data::class)->getCountriesWithOptionalZip(true) ?>
<script type="text/x-magento-init">
    {
        "#country_id": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= $block->getConfig('general/region/display_all') ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= /* @noEscape */ $this->helper(Data::class)->getRegionJson() ?>,
                "defaultRegion": "",
                "countriesWithOptionalZip": <?= /* @noEscape */ $countries ?>
            }
        },
        ".field.password": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-create-account"
            }
        },
        "#company-documents": {
            "Magento_Ui/js/core/app": <?= $block->getJsLayout() ?>
        },
        "#form-validate": {
            "Capgemini_ExponeaSubscription/js/onsubmit-subscription": {
                "emailInFormSelector": "#email_address",
                "confirmationCheckboxSelector": "#is_subscribed",
                "importSource": "Trade Account Application",
                "storeCode": "<?= $storeCode ?>",
                "sendToServer": true
            }
        }
    }
</script>
