<?php

/**
 * @copyright Copyright © 2021 Orba. All rights reserved.
 * @author    info@orba.co
 */

declare(strict_types=1);

/** @var \Orba\StyleGuide\Block\Section $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<h1 class="display-1"><?= $escaper->escapeHtml(__('H1 Display Heading')) ?></h1>
<h1 class="display-1-m"><?= $escaper->escapeHtml(__('H1 Display Heading Mobile')) ?></h1>
<h2 class="display-2"><?= $escaper->escapeHtml(__('H2 Display Heading')) ?></h2>
<h2 class="display-2-m"><?= $escaper->escapeHtml(__('H2 Display Heading Mobile')) ?></h2>
<h3 class="display-3"><?= $escaper->escapeHtml(__('H3 Display Heading')) ?></h3>
<h3 class="display-3-m"><?= $escaper->escapeHtml(__('H3 Display Heading Mobile')) ?></h3>

<hr/>

<h1><?= $escaper->escapeHtml(__('H1 Heading')) ?></h1>
<h2><?= $escaper->escapeHtml(__('H2 Heading')) ?></h2>
<h3><?= $escaper->escapeHtml(__('H3 Heading')) ?></h3>
<h4><?= $escaper->escapeHtml(__('H4 Heading')) ?></h4>
<h5><?= $escaper->escapeHtml(__('H5 Heading')) ?></h5>
<h6><?= $escaper->escapeHtml(__('H6 Heading')) ?></h6>
