<?php

/**
 * @copyright Copyright © 2021 Orba. All rights reserved.
 * @author    info@orba.co
 */

declare(strict_types=1);

/** @var \Orba\StyleGuide\Block\Section $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<div class="page messages">
    <div class="message success">
        <div>
            Success Message <a href="#">Link</a>
        </div>
    </div>
    <div class="message error">
        <div>
            Error Message <a href="#">Link</a>
        </div>
    </div>
    <div class="message warning">
        <div>
            Warning Message <a href="#">Link</a>
        </div>
    </div>
    <div class="message info">
        <div>
            Info Message <a href="#">Link</a>
        </div>
    </div>
</div>
