<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product additional attributes template
 *
 * @var $block \Lyonscg\Catalog\Block\Product\ProductList\Collection
 */
?>
<?php
$exist = $block->getItems()->getSize();
$type = 'related';
$class = $type;

$image = 'related_products_list';
$items = $block->getItems();
$limit = 0;
$shuffle = 0;
$canItemsAddToCart = $block->canItemsAddToCart();

$showAddTo = true;
$showCart = false;
$templateType = null;
$description = false;

/** @var \Lyonscg\Catalog\Helper\Data $_helper */
$_helper = $this->helper(\Lyonscg\Catalog\Helper\Data::class);
?>
<?php if ($exist) : ?>
    <div class="block-title title">
        <strong><?= __('Accessories'); ?></strong>
    </div>
<div class="block">
<div class="block <?= $block->escapeHtmlAttr($class) ?>"
     data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}'
     data-limit="<?= $block->escapeHtmlAttr($limit) ?>" data-shuffle="<?= /* @noEscape */ $shuffle ?>">
            <div class="block-content content" aria-labelledby="block-<?= $block->escapeHtmlAttr($class) ?>-heading">
                <div class="products wrapper grid products-grid products-<?= $block->escapeHtmlAttr($type) ?>">
                    <ol class="products list items product-items owl-carousel accesories-slider">
                        <?php foreach ($items as $_item):?>
                            <?php $available = ''; ?>
                            <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'):?>
                                <?php if (!$_item->getRequiredOptions()):?>
                                    <?php $available = 'related-available'; ?>
                                <?php endif; ?>
                            <?php endif; ?>
                            <?php if ($type == 'related' || $type == 'upsell'):?>
                        <li class="item product product-item" style="display: none;">
                            <?php else:?>
                        <li class="item product product-item">
                            <?php endif; ?>
                            <div class="product-item-info <?= /* @noEscape */ $available ?>">
                                <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
                                <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                   class="product photo product-item-photo">
                                    <?= $block->getImage($_helper->getChildProduct($_item), $image)->toHtml() ?>
                                </a>
                                <div class="product details product-item-details">
                                    <strong class="product name product-item-name"><a
                                            class="product-item-link"
                                            title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                                            href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>">
                                            <?= $block->escapeHtml($_item->getName()) ?></a>
                                    </strong>
                                    <?php if (!empty($_item->getDesigner())) : ?>
                                        <span class="designer_name"><?= $_item->getAttributeText('designer') ?></span>
                                    <?php endif; ?>

                                    <?= /* @noEscape */ $block->getProductPrice($_item) ?>

                                    <span class="price_info"><?= __('Price Varies'); ?></span> <!--TODO: get price info value-->

                                    <?php if ($templateType):?>
                                        <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                    <?php endif; ?>

                                    <!-- Swatches-->
                                    <?= $block->getProductDetailsHtml($_item) ?>

                                    <?php if ($canItemsAddToCart && !$_item->isComposite() && $_item->isSaleable()
                                    && $type == 'related'):?>
                                        <?php if (!$_item->getRequiredOptions()):?>
                                    <div class="field choice related"><input
                                            type="checkbox"
                                            class="checkbox related"
                                            id="related-checkbox<?= $block->escapeHtmlAttr($_item->getId()) ?>"
                                            name="related_products[]"
                                            value="<?= $block->escapeHtmlAttr($_item->getId()) ?>" />
                                        <label class="label"
                                            for="related-checkbox<?= $block->escapeHtmlAttr(
                                        $_item->getId()
                                    ) ?>"><span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                        </label>
                                    </div>
                                    <?php endif; ?>
                                    <?php endif; ?>

                                    <?php if ($showAddTo || $showCart):?>
                                        <?php // phpcs:disable?>
                                    <div class="product actions product-item-actions">
                                        <?php if ($showCart):?>
                                                <?php if ($_item->isSaleable()):?>
                                        <div class="actions-primary">
                                            <?php if (!$_item->getTypeInstance()->isPossibleBuyFromList($_item)):?>
                                            <button
                                                class="action tocart primary"
                                                data-mage-init='{"redirectUrl": {"url": "<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}' type="button" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                            </button>
                                            <?php else :?>
                                                <?php
                                            /** @var $viewModel PreparePostData */
                                            $viewModel = $block->getViewModel();
                                            $postArray = $viewModel->getPostData(
                                                $block->escapeUrl($block->getAddToCartUrl($_item)),
                                                ['product' => $_item->getEntityId()]
                                            );
                                            $value = $postArray['data'][ActionInterface::PARAM_NAME_URL_ENCODED];
                                            ?>
                                            <form data-role="tocart-form"
                                                  data-product-sku="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                                                  action="<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"
                                                  method="post">
                                                <input type="hidden" name="product"
                                                       value="<?= /* @noEscape */ (int)$_item->getEntityId() ?>">
                                                <input type="hidden"
                                                       name="<?= /* @noEscape */ ActionInterface::PARAM_NAME_URL_ENCODED?>"
                                                       value="<?= /* @noEscape */ $value ?>">
                                                <?= $block->getBlockHtml('formkey') ?>
                                                <button type="submit"
                                                        title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                        class="action tocart primary">
                                                    <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                </button>
                                            </form>
                                            <?php endif; ?>
                                                <?php else:?>
                                                    <?php if ($_item->getIsSalable()):?>
                                            <div class="stock available">
                                                <span><?= $block->escapeHtml(__('In stock')) ?></span>
                                            </div>
                                            <?php else:?>
                                            <div class="stock unavailable">
                                                <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                            </div>
                                            <?php endif; ?>
                                                <?php endif; ?>
                                        </div>
                                        <?php endif; ?>

                                            <?php if ($showAddTo):?>
                                        <div class="secondary-addto-links actions-secondary"
                                             data-role="add-to-links">
                                            <?php if ($addToBlock = $block->getChildBlock('addto')):?>
                                                        <?= $addToBlock->setProduct($_item)->getChildHtml() ?>
                                                    <?php endif; ?>
                                        </div>
                                        <?php endif; ?>
                                    </div>
                                    <?php // phpcs:enable?>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </li>
                        <?php endforeach ?>
                    </ol>
                </div>
            </div>
        </div>
        <?php if (!$block->isRedirectToCartEnabled() && $_item):?>
        <script type="text/x-magento-init">
            {
                "[data-role=tocart-form], .form.map.checkout": {
                    "catalogAddToCart": {
                        "product_sku": "<?= $block->escapeJs($_item->getSku()) ?>"
                    }
                }
            }
            </script>
<?php endif; ?>
</div>
<?php endif; ?>
