<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (http://www.amasty.com)
 * @package Amasty_Scroll
 */
/**
 * @var \Amasty\Scroll\Block\Init $block
 */
if ($block->isEnabled()) : ?>
    <script>
        require([
            'jquery',
            'amScrollScript'
        ], function ($) {
            var bodyElem = $('body');
            if ($.data(bodyElem[0], 'mage-amScrollScript')) {
                bodyElem.amScrollScript('initialize');
            } else {
                bodyElem.amScrollScript(<?= $block->getConfig();?>);
            }
        });
    </script>
<?php endif; ?>
