stage:
  global:
    SKIP_HTML_MINIFICATION: true
  build:
    SKIP_SCD: false
    SCD_STRATEGY: "compact"
    QUALITY_PATCHES:
      - MCLOUD-10279
      - MCLOUD-10226
      - ACSD-48784
      - ACSD-51149
      - B2B-2674
      - B2B-2598
      - ACSD-50817
      - ACSD-50858
      - ACSD-51431
      - ACSD-51857
      - ACSD-51265
      - ACSD-51102
  deploy:
    MYSQL_USE_SLAVE_CONNECTION: true
    REDIS_USE_SLAVE_CONNECTION: true
    REDIS_BACKEND: '\Magento\Framework\Cache\Backend\RemoteSynchronizedCache'
    CACHE_CONFIGURATION:
      _merge: true                        # Merge the configs with what already exists in env.php
      frontend:
        default:
          id_prefix: '061_'               # Prefix for keys to be preloaded
          backend_options:
            use_stale_cache: true         # Use old cache while new ones are being generated
            read_timeout: 10              # Default 5, more than that only to help with Redis issues
            connect_retries: 2            # More than that only to help with Redis sync issues
            compress_data: 4              # 0-9
            compress_tags: 4              # 0-9
            compress_threshold: 20480     # don't compress files smaller than this value
            compression_lib: 'gzip'       # snappy and lzf for performance, gzip for high compression (~69%)
            preload_keys:
              - '061_EAV_ENTITY_TYPES:hash'
              - '061_GLOBAL_PLUGIN_LIST:hash'
              - '061_DB_IS_UP_TO_DATE:hash'
              - '061_SYSTEM_DEFAULT:hash'
    SEARCH_CONFIGURATION:
      engine: opensearch
    CRON_CONSUMERS_RUNNER:
      cron_run: true
      max_messages: 1000
      consumers: [ ]
  post-deploy:
    WARM_UP_CONCURRENCY: 8
    WARM_UP_PAGES:
      - "index.php"
      - "ceiling"
      - "wall"
      - "table"
      - "floor"
      - "outdoor"
      - "fans"
      - "architectural"
      - "sale"
