<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
 * @package Store Locator for Magento 2
 */
?>
<?php
/**
 * @var \Amasty\Storelocator\Block\View\Schedule $block
 * @var \Amasty\Storelocator\Model\Location $location
 */
$location = $block->getLocation();
$workToday = $location->getWorkingTimeToday();
?>

<div class="amlocator-schedule-container">
    <div class="amlocator-today"  data-amlocator-js="collapse-trigger">
        <strong><?= $block->escapeHtml(__('Monday - Friday')); ?></strong>
        <span class="amlocator-time">
            <span><?= $block->escapeHtml($workToday); ?></span>
        </span>
    </div>

    <div class="amlocator-schedule-table">
        <?php foreach ($location->dayNames as $key => $item) {
            $workingTime = $location->getWorkingTime($key);
            ?>
            <?php if ($key == 'saturday') :?>
            <div class="amlocator-row">
                <?php foreach ($workingTime as $keyTime => $time) { ?>
                    <span class="amlocator-cell -day"><?= $block->escapeHtml(__($keyTime)) ?></span>
                    <span class="amlocator-cell -time"><?= $block->escapeHtml(__($time)) ?></span>
                <?php } ?>
            </div>
            <?php endif; ?>
        <?php } ?>
    </div>

</div>