<?php
/** @var \Capgemini\BloomreachWidget\Block\Widget $block */
?>

<?php $toRender = $block->obtainData() ?>
<?php if (!empty($toRender)): ?>
    <div class="widget-type"><?= $block->widgetTitle() ?></div>
    <div class="br-widget products">
        <ul class="br-widget more-results">
                <?php foreach ($toRender as $item): ?>
                    <li>
                        <div class="br-image-wrapper">
                            <a href="<?= $item['url'] ?>"><img src="<?= $item['image'] ?>" alt="<?= $item['title'] ?>"/></a>
                        </div>
                        <a href="<?= $item['url'] ?>" class="title"><?= ucwords($item['title']) ?></a>
                        <?php if($block->isShowDescription()) : ?><span class="description"><?= $item['description']; ?></span><?php endif; ?>
                        <a href="<?= $item['url'] ?>" class="view-details">View Additional Finishes</a>
                    </li>
                <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
