<?php
/** @var $block \Capgemini\OrderView\Block\Orders */
$limit = $block->getRequest()->getParam('limit') ?? $block::INITIAL_LIMIT;
$page = $block->getRequest()->getParam('p') ?? 1;

$customerId = $block->getCustomerId();
 
if ($block->getCustomerType() == \Capgemini\CompanyType\Model\Config::WHOLESALE) {
    $customerNumber = $this->getRequest()->getParam('account_id') ?? $block->getCustomerVcNumber();
} else {
    $customerNumber = $block->getCustomerNumber();
}
$filtersParams = [];

foreach (['orderstatus','division'] as $filtersParam)
{
    if($this->getRequest()->getParam($filtersParam))
    {
        $filtersParams[$filtersParam] = $this->getRequest()->getParam($filtersParam);
    }
}

$orders = $block->getOrders($page, $limit, $customerNumber, $filtersParams);
$filters = $block->getFilter();
$searchbal = '';
if($this->getRequest()->getParam('search'))
{
    $searchbal = $this->getRequest()->getParam('search');
}
$customerVcNumber =  $customerNumber;
$params = $block->getRequest()->getParams();
$searchParams = $params;
?>
<?php if($block->getCustomerType() == \Capgemini\CompanyType\Model\Config::WHOLESALE) : ?>

<?php endif;?>
<div id="order-list-main"> 
    <?php if ($orders && count($orders)): ?>
        <div class="table-wrapper orders-history data-grid-wrap orderspages" id="order-list-wrap">
           
                <?php if($block->getCustomerType() != \Capgemini\CompanyType\Model\Config::WHOLESALE) : ?> <th scope="col" class="data-grid-th col job"><?= $block->escapeHtml(__('Job Name')) ?></th><?php endif; ?>
             
                <?php if($block->getCustomerType() != \Capgemini\CompanyType\Model\Config::WHOLESALE) : ?>  <th scope="col" class="data-grid-th col total"><?= $block->escapeHtml(__('Order Total')) ?></th><?php endif; ?>
                   
                    <?php if(!empty($block->getOrderFilter('orderstatus'))): ?>
                       
                        <div class="status-dropdown">
                            <ul class="header links">
                                <?php foreach ($block->getOrderFilter('orderstatus') as $status): $searchParams['orderstatus'] = $status; if($this->getRequest()->getParam('orderstatus') === $status) { unset($searchParams['orderstatus']); } ?>
                                    <li data-action="status-filter">
                                        <span class="statuscheckbox">
                                            <input type="checkbox" value="<?= $status ?>" <?= ($this->getRequest()->getParam('orderstatus') === $status)? 'checked="checked"':''; ?> />
                                        <?= $status ?></span>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                   
                    <?php endif;?>
              
              
               
        </div>
        <?php endif;?>
</div>



<script>
require(['jquery', 'Capgemini_OrderView/js/widget/sortable-table'], function($) {

$('.sortable-table').sortableTable();

$(document).ready(function(){

    var url = window.location.href;
var sortType = "";

var match = url.match(/\/sort_by\/([^\/]+)/);
if (match && match[1]) {
sortType = match[1];
}

const element = document.querySelector("." + sortType);
    if(sortType){
        element.classList.add("active");
        console.log(element.nextSibling.nextElementSibling);
        element.nextSibling.nextElementSibling.classList.remove("active");
    }
});

});
</script>
