<?php
/**
 * PDF Requisition List Template
 *
 * @category  Lyons
 * @package   Lyonscg_RequisitionList
 * @author    Tanya Mamchik <tanya.mamchik@capgemini.com>
 * @copyright Copyright (c) 2020 Lyons Consulting Group (www.lyonscg.com)
 */

/* @var $block \Magento\RequisitionList\Block\Requisition\Item\Options */
?>
<?php $options = $block->getOptionList(); ?>
<?php if ($options) : ?>
    <?php foreach ($options as $option) : ?>
        <div class="item-option font-14">
            <span><?= $block->escapeHtml($option['label']) ?>: </span>
            <?php if (is_array($option['value'])) : ?>
                <?= /* @noEscape */ nl2br($block->escapeHtml(implode("\n", $option['value']))) ?>
            <?php elseif (isset($option['option_type']) && $option['option_type'] == 'file') : ?>
                <?php $viewModel = $block->getData('downloadableViewModel'); ?>
                <?php $viewModel->setItem($block->getItem()) ?>
                <?= /* @noEscape */ $viewModel->getOptionValueForFile($option) ?>
            <?php else : ?>
                <?= $block->escapeHtml($option['value']) ?>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
<?php endif ?>
