<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var \Magento\Wishlist\Block\Share\Email\Items $block */
?>
<?php
    $l = $block->getWishlistItemsCount();
    /** @var \Lyonscg\Catalog\Helper\Data $_helper */
    $_helper = $this->helper(\Lyonscg\Catalog\Helper\Data::class);
?>
<div>
    <table>
        <tr>
            <?php $i = 0;
            foreach ($block->getWishlistItems() as $item) : $i++ ?>
                <?php /* @var $item \Magento\Wishlist\Model\Item */ ?>
                <?php /* @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php $_product = $item->getProduct(); ?>
                <?php $_simpleProduct = $_helper->getChildProduct($_product); ?>
                <?php $productForThumbnail = $block->getProductForThumbnail($item); ?>
            <td class="col product">
                    <p>
                        <a href="<?= $block->escapeUrl($block->getProductUrl($_product)) ?>">
                            <?php if ($productForThumbnail->getThumbnail() == 'no_selection' || $productForThumbnail->getTypeId() == 'configurable') : ?>
                                <?= /* @noEscape */ $block->getImage($_simpleProduct, 'product_small_image')->toHtml() ?>
                            <?php else : ?>
                                <?= $block->getImage($block->getProductForThumbnail($item), 'product_small_image')->toHtml() ?>
                            <?php endif; ?>
                        </a>
                    </p>

                    <p>
                        <a href="<?= $block->escapeUrl($block->getProductUrl($_product)) ?>">
                            <strong><?= $block->escapeHtml($_product->getName()) ?></strong>
                        </a>
                    </p>
                    <?php if ($block->hasDescription($item)) : ?>
                        <p>
                            <strong><?= $block->escapeHtml(__('Comment')) ?>:</strong>
                            <br/><?= /* @noEscape */  $block->getEscapedDescription($item) ?>
                        </p>
                    <?php endif; ?>
                    <p>
                        <a href="<?= $block->escapeUrl($block->getProductUrl($_product)) ?>">
                            <?= $block->escapeHtml(__('View Product')) ?>
                        </a>
                    </p>
                </td>
                <?php if ($i % 3 != 0) : ?>
                    <td></td>
                <?php else : ?>
            </tr>
            <tr>
                <td colspan="5">&nbsp;</td>
            </tr>
                    <?php if ($i < $l) : ?>
                    <tr>
                    <?php endif ?>
                <?php endif ?>
            <?php endforeach ?>
    </table>
</div>
