<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */

/** ex: \Magento\Catalog\Pricing\Price\FinalPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */

$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
$price = $block->getApiPrice();
?>
<?= /* @noEscape */ $block->renderAmount($finalPriceModel->getCustomAmount($price), [
    'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
    'price_type'        => 'finalPrice',
    'include_container' => true,
    'schema' => $schema
]); ?>
