<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var Magento\CustomerCustomAttributes\Block\Form $block */

use Magento\Customer\Block\Widget\Dob;
use Magento\Customer\Block\Widget\Gender;
use Magento\Customer\Block\Widget\Name;
use Magento\Customer\Block\Widget\Taxvat;

/** @var \Capgemini\CompanyType\ViewModel\AccountPermissions $accountPermissions */
$accountPermissions = $block->getData('account_permissions');
$canChangeName = !$accountPermissions || $accountPermissions->canChangeName();
$canChangeEmail = !$accountPermissions || $accountPermissions->canChangeName();
?>
<form class="form form-edit-account" action="<?= /* @noEscape */ $block->getUrl('customer/account/editPost') ?>"
      method="post" id="form-validate" enctype="multipart/form-data"
      data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>" autocomplete="off"
>
    <div class="fieldset__wrapper">
        <fieldset class="fieldset info">
            <?= $block->getBlockHtml('formkey') ?>
            <legend class="legend hidden-mobile"><span><?= $block->escapeHtml(__('Account Information')) ?></span></legend><br>

            <?php if ($canChangeName) : ?>
                <?= $block->getLayout()->createBlock(Name::class)->setObject($block->getCustomer())->toHtml() ?>
            <?php else: ?>
                <p class="name">
                    <?= $block->escapeHtml($block->getCustomer()->getFirstname() . $block->getCustomer()->getLastName()) ?>
                </p>
                <input type="hidden" name="firstname" value="<?= $block->escapeHtml($block->getCustomer()->getFirstname()) ?>">
                <input type="hidden" name="lastname" value="<?= $block->escapeHtml($block->getCustomer()->getLastName()) ?>">
            <?php endif; ?>

            <?php $_dob = $block->getLayout()->createBlock(Dob::class) ?>
            <?php $_taxvat = $block->getLayout()->createBlock(Taxvat::class) ?>
            <?php $_gender = $block->getLayout()->createBlock(Gender::class) ?>
            <?php if ($_dob->isEnabled()): ?>
                <?= $_dob->setDate($block->getCustomer()->getDob())->toHtml() ?>
            <?php endif ?>
            <?php if ($_taxvat->isEnabled()): ?>
                <?= $_taxvat->setTaxvat($block->getCustomer()->getTaxvat())->toHtml() ?>
            <?php endif ?>
            <?php if ($_gender->isEnabled()): ?>
                <?= $_gender->setGender($block->getCustomer()->getGender())->toHtml() ?>
            <?php endif ?>
            <?php if ($canChangeEmail) : ?>
                <div class="field choice">
                    <input type="checkbox" name="change_email" id="change-email" data-role="change-email" value="1"
                           title="<?= $block->escapeHtmlAttr(__('Change Email')) ?>" class="checkbox"
                    />
                    <label class="label" for="change-email">
                        <span><?= $block->escapeHtml(__('Change Email')) ?></span>
                    </label>
                </div>
            <?php else: ?>
                <p class="email">
                    <?= $block->escapeHtml($block->getCustomer()->getEmail()) ?>
                </p>
            <?php endif; ?>

            <div class="field choice">
                <input type="checkbox" name="change_password" id="change-password" data-role="change-password" value="1"
                       title="<?= $block->escapeHtmlAttr(__('Change Password')) ?>"
                    <?php if ($block->getChangePassword()): ?> checked="checked"<?php endif; ?> class="checkbox"
                />
                <label class="label" for="change-password">
                    <span><?= $block->escapeHtml(__('Change Password')) ?></span>
                </label>
            </div>

            <?php $userDefinedAttributes = $block->getLayout()->getBlock('customer_form_user_attributes'); ?>
            <?php if ($userDefinedAttributes): ?>
                <?php $userDefinedAttributes->setEntityType('customer')->setShowContainer(false);?>
                <?php $block->restoreSessionData($userDefinedAttributes->getMetadataForm());?>
                <?= $userDefinedAttributes->toHtml() ?>
            <?php endif;?>

            <?= $block->getChildHtml('fieldset_edit_info_additional') ?>
            <?= /* @noEscape */ $block->getChildHtml('form_fields_before_in_form') ?>

            <?php if (!$canChangeName) : ?>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button type="button" class="action primary" title="<?= $block->escapeHtmlAttr(__('Request Account Changes')) ?>"
                                onclick="window.location='<?= $block->escapeHtml($block->getUrl('contact')) ?>'">
                            <span><?= $block->escapeHtml(__('Request Account Changes')) ?></span>
                        </button>
                    </div>
                </div>
            <?php endif; ?>
        </fieldset>

        <div class="actions-toolbar hidden-desktop">
            <div class="primary">
                <?php if ($canChangeName) : ?>
                    <button type="submit" class="action save primary" title="<?= $block->escapeHtmlAttr(__('Save Changes')) ?>">
                        <span><?= $block->escapeHtml(__('Save Changes')) ?></span>
                    </button>
                <?php endif; ?>
            </div>
        </div>

        <fieldset class="fieldset password" data-container="change-email-password">
            <legend class="legend">
                <span data-title="change-email-password"><?= $block->escapeHtml(__('Change Email and Password')) ?></span>
            </legend><br>
            <div class="field email required" data-container="change-email">
                <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                <div class="control">
                    <input type="email" autocomplete="email" name="email" id="email" data-input="change-email"
                           value="<?= $block->escapeHtml($block->getCustomer()->getEmail()) ?>"
                           title="<?= $block->escapeHtmlAttr(__('Email')) ?>" class="input-text"
                           data-validate="{required:true, 'validate-email':true}"
                    />
                </div>
            </div>
            <div class="field password current required">
                <label class="label" for="current-password">
                    <span><?= $block->escapeHtml(__('Current Password')) ?></span>
                </label>
                <div class="control">
                    <input type="password" class="input-text" name="current_password" id="current-password"
                           data-input="current-password" autocomplete="off"
                    />
                </div>
            </div>
            <div class="field new password required" data-container="new-password">
                <label class="label" for="password">
                    <span><?= $block->escapeHtml(__('New Password')) ?></span>
                </label>
                <div class="control">
                    <?php $minCharacterSets = $block->getRequiredCharacterClassesNumber() ?>
                    <input type="password" class="input-text" name="password" id="password"
                           data-password-min-length="<?= $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
                           data-password-min-character-sets="<?= $block->escapeHtml($minCharacterSets) ?>"
                           data-input="new-password"
                           data-validate="{required:true, 'validate-customer-password':true}"
                           autocomplete="off" />
                    <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                        <div id="password-strength-meter" class="password-strength-meter">
                            <?= $block->escapeHtml(__('Password Strength')) ?>:
                            <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                            <?= $block->escapeHtml(__('No Password')) ?>
                        </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="field confirm password required" data-container="confirm-password">
                <label class="label" for="password-confirmation">
                    <span><?= $block->escapeHtml(__('Confirm New Password')) ?></span>
                </label>
                <div class="control">
                    <input type="password" class="input-text" name="password_confirmation" id="password-confirmation"
                           data-input="confirm-password" autocomplete="off"
                    />
                </div>
            </div>
            <div class="field choice" data-bind="scope: 'showPassword'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
            <?php if(!$canChangeName): ?>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button type="submit" class="action save primary" title="<?= $block->escapeHtmlAttr(__('Save Changes')) ?>">
                            <span><?= $block->escapeHtml(__('Save Changes')) ?></span>
                        </button>
                    </div>
                </div>
            <?php endif; ?>
        </fieldset>
<!--        <fieldset class="fieldset additional_info">-->
            <?php /* echo $block->getChildHtml('form_additional_info') */?>
<!--        </fieldset>-->
    </div>

    <div class="actions-toolbar hidden-mobile">
        <div class="primary">
            <?php if ($canChangeName) : ?>
                <button type="submit" class="action save primary" title="<?= $block->escapeHtmlAttr(__('Save Changes')) ?>">
                    <span><?= $block->escapeHtml(__('Save Changes')) ?></span>
                </button>
            <?php endif; ?>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
                <span><?= $block->escapeHtml(__('Go back')) ?></span>
            </a>
        </div>
    </div>
</form>
<script>
    require([
        "jquery",
        "mage/mage"
    ], function($){
        var dataForm = $('#form-validate');
        var ignore = <?= /* @noEscape */ $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null' ?>;

        dataForm.mage('validation', {
            <?php if ($_dob->isEnabled()): ?>
            errorPlacement: function(error, element) {
                if (element.prop('id').search('full') !== -1) {
                    var dobElement = $(element).parents('.customer-dob'),
                        errorClass = error.prop('class');
                    error.insertAfter(element.parent());
                    dobElement.find('.validate-custom').addClass(errorClass)
                        .after('<div class="' + errorClass + '"></div>');
                }
                else {
                    error.insertAfter(element);
                }
            },
            ignore: ':hidden:not(' + ignore + ')'
            <?php else: ?>
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
            <?php endif ?>
        });

    });
</script>
<script type="text/x-magento-init">
    {
        "[data-role=change-email], [data-role=change-password]": {
            "changeEmailPassword": {
                "titleChangeEmail": "<?= $block->escapeJs(__('Change Email')) ?>",
                "titleChangePassword": "<?= $block->escapeJs(__('Change Password')) ?>",
                "titleChangeEmailAndPassword": "<?= $block->escapeJs(__('Change Email and Password')) ?>"
            }
        },
        "*": {
            "Magento_CustomerCustomAttributes/validation": {
                "ignore": <?= (int) ($_dob->isEnabled() || $userDefinedAttributes->hasUserDefinedAttributes()) ?>,
                "hasUserDefinedAttributes": <?= (int) $userDefinedAttributes->hasUserDefinedAttributes() ?>,
                "isDobEnabled": <?= (int) $_dob->isEnabled() ?>,
                "mixins": [
                    "Magento_CustomerCustomAttributes/error-placement",
                    "Magento_CustomerCustomAttributes/validation-ignore"
                ]
            },
            "Magento_Ui/js/core/app": {
                "components": {
                    "showPassword": {
                        "component": "Magento_Customer/js/show-password",
                        "passwordSelector": "#current-password,#password,#password-confirmation"
                    }
                }
            }
        },
        "[data-container=new-password]": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-edit-account"
            }
        }
    }
</script>
