<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Info $block */

/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();

/** @var \Lyonscg\Catalog\Helper\Data $_helper */
$_helper = $this->helper(\Lyonscg\Catalog\Helper\Data::class);
$childProduct = $_helper->getChildProduct($product);
?>
<strong class="product-item-name">
    <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>" title="<?= $block->escapeHtmlAttr($product->getName()) ?>" class="product-item-link">
        <?= $block->escapeHtml($product->getName()) ?>
    </a>
</strong>
<?php if (!empty($childProduct->getBrand())) : ?>
	<span class="business_collection"><?= $childProduct->getAttributeText('brand') ?></span>
<?php endif; ?>
<?php if (!empty($childProduct->getDesigner())) : ?>
    <span class="designer_name"><?= $childProduct->getAttributeText('designer') ?></span>
<?php endif; ?>