<?php /** @var \Plumrocket\Checkoutspage\Block\Item\Renderer\DefaultRenderer $block */ ?>
<?php /** @var \Magento\Framework\Escaper $escaper */ ?>

<?php

use Magento\ConfigurableProduct\Model\Product\Type\Configurable;
//order.success.additional.info
$item = $block->getItem();
$product = $item->getProduct();
$priceHelper = $this->helper(Magento\Framework\Pricing\Helper\Data::class);
$_itemExt = $item->getExtensionAttributes();
$sidemark = '';
$comments = '';
if ($_itemExt) {
    $sidemark = $_itemExt->getSidemark();
    $comments = $_itemExt->getCommentsLineItem();
}
if (!$sidemark) {
    $sidemark = $item->getSidemark();
}
if (!$comments) {
    $comments = $item->getCommentsLineItem();
}

$brandText = $product->getAttributeText('brand');
$designerText = $product->getAttributeText('designer');

// Availability
if ($product->getTypeId() === Configurable::TYPE_CODE) {
    $children = $this->getItem()->getChildrenItems();
    if (count($children)) {
        $itemProduct = $children[0]->getProduct();
    }
} else {
    $itemProduct = $product;
}
?>
<tbody class="cart item">
<tr class="item-info">
    <td data-th="Product" class="col item">

        <a class="product-item-photo">
            <?= /* @noEscape */ $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
        </a>

        <div class="product-item-details">
            <strong class="product name product-item-name"><?= $escaper->escapeHtml($item->getName()) ?></strong>

            <?php if ($brandText && $designerText):?>
                <div class="product-item-info-extra">
                    <span class="brand"><?= $brandText ?></span>
                    <span class="designer"><?= $designerText ?></span>
                </div>
            <?php endif; ?>

            <div class="product-item-sku">
                <span><?= $escaper->escapeHtml(__('Item #:')) ?></span>
                <?= /* @noEscape */ $block->prepareSku($block->getSku()) ?>
            </div>


            <div class="product-stock">
                <?php if ($itemProduct->getAvailabilityMessage()): ?>
                    <span><?= $escaper->escapeHtml(__('Availability:')) ?></span>
                    <?= $escaper->escapeHtml(__($itemProduct->getAvailabilityMessage())) ?>
                <?php endif; ?>
            </div>

            <?php if ($options = $block->getItemOptions()): ?>
                <dl class="item-options">
                    <?php foreach ($options as $option): ?>
                        <dt><?= $escaper->escapeHtml($option['label']) ?></dt>
                        <dd>
                            <?php if (! $block->getPrintStatus()): ?>
                                <?php $formattedOptionValue = $block->getFormatedOptionValue($option) ?>
                                <?php if (isset($formattedOptionValue['full_view'])): ?>
                                    <?= /* @noEscape */ $formattedOptionValue['full_view'] ?>
                                <?php else: ?>
                                    <?= /* @noEscape */ $formattedOptionValue['value'] ?>
                                <?php endif; ?>
                            <?php else: ?>
                                <?= /* @noEscape */nl2br($escaper->escapeHtml(($option['print_value'] ?? $option['value']))) ?>
                            <?php endif; ?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            <?php endif; ?>

            <?php if ($sidemark):?>
                <div class="sidemark hidden-mobile">
                    <span class="label"><?= $escaper->escapeHtml(__('Sidemark')) ?></span>
                    <p><?= $escaper->escapeHtml($sidemark) ?></p>
                </div>
            <?php endif; ?>

            <?php if ($comments):?>
                <div class="comments hidden-mobile">
                    <span class="label"><?= $escaper->escapeHtml(__('Comments')) ?></span>
                    <p><?= $escaper->escapeHtml($comments) ?></p>
                </div>
            <?php endif; ?>
        </div>
    </td>


    <td class="col price" data-th="Price">
        <?= /* @noEscape */ $priceHelper->currency($block->getItem()->getPrice(), true, false) ?>
    </td>

    <td class="col qty" data-th="Qty">
    <?php if ($block->getItem()->getQtyOrdered() > 0): ?>
        <span class="content"><?= /* @noEscape */ (int)$block->getItem()->getQtyOrdered() ?></span>
    <?php endif; ?>
    </td>

    <td class="col subtotal" data-th="Subtotal">
        <?= $block->getItemRowTotalHtml() ?>
    </td>

    <td class="hidden-desktop">
        <?php if ($sidemark): ?>
            <div class="sidemark">
                <span class="label"><?= $escaper->escapeHtml(__('Sidemark')) ?></span>
                <p><?= $escaper->escapeHtml($sidemark) ?></p>
            </div>
        <?php endif; ?>

        <?php if ($comments):?>
            <div class="comments">
                <span class="label"><?= $escaper->escapeHtml(__('Comments')) ?></span>
                <p><?= $escaper->escapeHtml($comments) ?></p>
            </div>
        <?php endif; ?>
    </td>
</tr>
</tbody>
