<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Sales\Block\Order\Totals
 * @see \Magento\Sales\Block\Order\Totals
 */
$helper = $this->helper('Capgemini\OrderView\Helper\Data');

$customerType = $helper->getCustomerType();
if($customerType != \Capgemini\CompanyType\Model\Config::WHOLESALE) :
?>
<div class="totals-container">
    <dl class="totals-container-inner">
    <div>
        <dt><strong><?= $block->escapeHtml(__('Summary')) ?></strong></dt>
    </div>
    <?php foreach ($block->getTotals() as $_code => $_total) : ?>
        <?php if (trim($_total->getLabel())): ?>
            <div class="total-row <?= $block->escapeHtmlAttr($_code) ?>">
                <dt>
                    <?php if ($_total->getStrong()) : ?>
                        <strong><?= $block->escapeHtml($_total->getLabel()) ?></strong>
                    <?php else : ?>
                        <?= $block->escapeHtml($_total->getLabel()) ?>
                    <?php endif ?>
                </dt>
                <dd>
                    <?php if ($_total->getStrong()) : ?>
                        <strong><?= /* @noEscape */ $block->formatValue($_total) ?></strong>
                    <?php else : ?>
                        <?= /* @noEscape */ $block->formatValue($_total) ?>
                    <?php endif ?>
                </dd>
            </div>
        <?php endif; ?>
    <?php endforeach?>
    </dl>
</div>
<?php endif;?>
