<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php $_product = $block->getProduct() ?>

<?php if ($block->displayProductStockStatus()) :?>
    <div class="stock available" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
        <span><?= $_product->getAttributeText(\Capgemini\Configurable\Block\Configurable\Child::AVAILABILITY_ATTRIBUTE_CODE) ?></span>
    </div>
<?php endif; ?>
