<?php
/**
 * MOCK DATA USED FOR STYLING PRODUCT GRID (Tyler Hebel)
 */
$mockData = [
    [
        'name' => 'Element',
        'anchor' => 'element',
        'blurb' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut suscipit nunc in turpis consequat bibendum. Mauris id aliquam mauris. Ut sit amet urna arcu. Quisque a lorem in risus egestas interdum ac tincidunt nisi Donec semper tellus maximus, porta lacus et, tristique dui. Curabitur at molestie neque. Nunc est lorem, eleifend sit amet ex eu, eleifend fringilla arcu..',
        'products' => [
            [
                'name' => 'ELEMENT 2" LED',
                'img' => $this->getViewFileUrl('images/tech-lighting/tech-product-element.jpg'),
                'trim_options' => [
                    'Square Flanged & Flangless',
                    'Round Flanged & Flangless',
                ],
                'housing_options' => [
                    'Adjustable and Wall Wash',
                    'Remodel Adjustable and Wall Wash',
                    'Ultra-Shallow Fixed',
                ],
                'attributes' => [
                    'Source' => 'LED',
                    'Source lumens' => '925 - 2475 lm',
                    'Delivered Lumens' => '775 - 2025 lm',
                    'Beamspreads' => '10° - 60°, WW'
                ]
            ],
            [
                'name' => 'ELEMENT 3" LED',
                'img' => $this->getViewFileUrl('images/tech-lighting/tech-product-element.jpg'),
                'trim_options' => [
                    'Square Flanged & Flangless',
                    'Round Flanged & Flangless',
                ],
                'housing_options' => [
                    'Adjustable - Next Generation',
                    'Fixed - Next Generation',
                    'Wall Wash - Next Generation',
                    'Low-Profile Fixed',
                    'Ultra-Shallow Fixed',
                    'Shallow Adjustable - NEW',
                    'Dual Adjustable',
                    'Remodel Adjustable Non-IC',
                    'Remodel Fixed Non-IC',
                    'Remodel Adjustable and New Construction IC - NEW',
                ],
                'attributes' => [
                    'Source' => 'HALOGEN',
                    'Source lumens' => '925 - 2475 lm',
                    'Delivered Lumens' => '775 - 2025 lm',
                    'Beamspreads' => '10° - 60°, WW'
                ]
            ],
            [
                'name' => 'ELEMENT 2" LED',
                'img' => $this->getViewFileUrl('images/tech-lighting/tech-product-element.jpg'),
                'trim_options' => [
                    'Square Flanged & Flangless',
                    'Round Flanged & Flangless',
                ],
                'housing_options' => [
                    'Adjustable and Wall Wash',
                    'Remodel Adjustable and Wall Wash',
                    'Ultra-Shallow Fixed',
                ],
                'attributes' => [
                    'Source' => 'LED',
                    'Source lumens' => '925 - 2475 lm',
                    'Delivered Lumens' => '775 - 2025 lm',
                    'Beamspreads' => '10° - 60°, WW'
                ]
            ],
            [
                'name' => 'ELEMENT 2" LED',
                'img' => $this->getViewFileUrl('images/tech-lighting/tech-product-element.jpg'),
                'trim_options' => [
                    'Square Flanged & Flangless',
                    'Round Flanged & Flangless',
                ],
                'housing_options' => [
                    'Adjustable and Wall Wash',
                    'Remodel Adjustable and Wall Wash',
                    'Ultra-Shallow Fixed',
                ],
                'attributes' => [
                    'Source' => 'LED',
                    'Source lumens' => '925 - 2475 lm',
                    'Delivered Lumens' => '775 - 2025 lm',
                    'Beamspreads' => '10° - 60°, WW'
                ]
            ],
            [
                'name' => 'ELEMENT 2" LED',
                'img' => $this->getViewFileUrl('images/tech-lighting/tech-product-element.jpg'),
                'trim_options' => [
                    'Square Flanged & Flangless',
                    'Round Flanged & Flangless',
                ],
                'housing_options' => [
                    'Adjustable and Wall Wash',
                    'Remodel Adjustable and Wall Wash',
                    'Ultra-Shallow Fixed',
                ],
                'attributes' => [
                    'Source' => 'LED',
                    'Source lumens' => '925 - 2475 lm',
                    'Delivered Lumens' => '775 - 2025 lm',
                    'Beamspreads' => '10° - 60°, WW'
                ]
            ],
        ]
    ],
    [
        'name' => 'Entra',
        'anchor' => 'entra',
        'blurb' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut suscipit nunc in turpis consequat bibendum. Mauris id aliquam mauris. Ut sit amet urna arcu. Quisque a lorem in risus egestas interdum ac tincidunt nisi Donec semper tellus maximus, porta lacus et, tristique dui. Curabitur at molestie neque. Nunc est lorem, eleifend sit amet ex eu, eleifend fringilla arcu..',
        'products' => [
            [
                'name' => 'ELEMENT 2" LED',
                'img' => $this->getViewFileUrl('images/tech-lighting/tech-product-entra.jpg'),
                'trim_options' => [
                    'Square Flanged & Flangless',
                    'Round Flanged & Flangless',
                ],
                'housing_options' => [
                    'Adjustable and Wall Wash',
                    'Remodel Adjustable and Wall Wash',
                    'Ultra-Shallow Fixed',
                ],
                'attributes' => [
                    'Source' => 'LED',
                    'Source lumens' => '925 - 2475 lm',
                    'Delivered Lumens' => '775 - 2025 lm',
                    'Beamspreads' => '10° - 60°, WW'
                ]
            ],
            [
                'name' => 'ELEMENT 3" LED',
                'img' => $this->getViewFileUrl('images/tech-lighting/tech-product-entra.jpg'),
                'trim_options' => [
                    'Square Flanged & Flangless',
                    'Round Flanged & Flangless',
                ],
                'housing_options' => [
                    'Adjustable - Next Generation',
                    'Fixed - Next Generation',
                    'Wall Wash - Next Generation',
                    'Low-Profile Fixed',
                    'Ultra-Shallow Fixed',
                    'Shallow Adjustable - NEW',
                    'Dual Adjustable',
                    'Remodel Adjustable Non-IC',
                    'Remodel Fixed Non-IC',
                    'Remodel Adjustable and New Construction IC - NEW',
                ],
                'attributes' => [
                    'Source' => 'HALOGEN',
                    'Source lumens' => '925 - 2475 lm',
                    'Delivered Lumens' => '775 - 2025 lm',
                    'Beamspreads' => '10° - 60°, WW'
                ]
            ],
            [
                'name' => 'ELEMENT 2" LED',
                'img' => $this->getViewFileUrl('images/tech-lighting/tech-product-entra.jpg'),
                'trim_options' => [
                    'Square Flanged & Flangless',
                    'Round Flanged & Flangless',
                ],
                'housing_options' => [
                    'Adjustable and Wall Wash',
                    'Remodel Adjustable and Wall Wash',
                    'Ultra-Shallow Fixed',
                ],
                'attributes' => [
                    'Source' => 'LED',
                    'Source lumens' => '925 - 2475 lm',
                    'Delivered Lumens' => '775 - 2025 lm',
                    'Beamspreads' => '10° - 60°, WW'
                ]
            ],
            [
                'name' => 'ELEMENT 2" LED',
                'img' => $this->getViewFileUrl('images/tech-lighting/tech-product-entra.jpg'),
                'trim_options' => [
                    'Square Flanged & Flangless',
                    'Round Flanged & Flangless',
                ],
                'housing_options' => [
                    'Adjustable and Wall Wash',
                    'Remodel Adjustable and Wall Wash',
                    'Ultra-Shallow Fixed',
                ],
                'attributes' => [
                    'Source' => 'LED',
                    'Source lumens' => '925 - 2475 lm',
                    'Delivered Lumens' => '775 - 2025 lm',
                    'Beamspreads' => '10° - 60°, WW'
                ]
            ],
            [
                'name' => 'ELEMENT 2" LED',
                'img' => $this->getViewFileUrl('images/tech-lighting/tech-product-entra.jpg'),
                'trim_options' => [
                    'Square Flanged & Flangless',
                    'Round Flanged & Flangless',
                ],
                'housing_options' => [
                    'Adjustable and Wall Wash',
                    'Remodel Adjustable and Wall Wash',
                    'Ultra-Shallow Fixed',
                ],
                'attributes' => [
                    'Source' => 'LED',
                    'Source lumens' => '925 - 2475 lm',
                    'Delivered Lumens' => '775 - 2025 lm',
                    'Beamspreads' => '10° - 60°, WW'
                ]
            ],
        ]
    ],
    [
        'name' => 'Reflections',
        'anchor' => 'reflections',
        'blurb' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut suscipit nunc in turpis consequat bibendum. Mauris id aliquam mauris. Ut sit amet urna arcu. Quisque a lorem in risus egestas interdum ac tincidunt nisi Donec semper tellus maximus, porta lacus et, tristique dui. Curabitur at molestie neque. Nunc est lorem, eleifend sit amet ex eu, eleifend fringilla arcu..',
        'products' => [
            [
                'name' => 'ELEMENT 2" LED',
                'img' => $this->getViewFileUrl('images/tech-lighting/tech-product-reflections.jpg'),
                'trim_options' => [
                    'Square Flanged & Flangless',
                    'Round Flanged & Flangless',
                ],
                'housing_options' => [
                    'Adjustable and Wall Wash',
                    'Remodel Adjustable and Wall Wash',
                    'Ultra-Shallow Fixed',
                ],
                'attributes' => [
                    'Source' => 'LED',
                    'Source lumens' => '925 - 2475 lm',
                    'Delivered Lumens' => '775 - 2025 lm',
                    'Beamspreads' => '10° - 60°, WW'
                ]
            ]
        ]
    ],
    [
        'name' => 'Verse',
        'anchor' => 'verse',
        'blurb' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut suscipit nunc in turpis consequat bibendum. Mauris id aliquam mauris. Ut sit amet urna arcu. Quisque a lorem in risus egestas interdum ac tincidunt nisi Donec semper tellus maximus, porta lacus et, tristique dui. Curabitur at molestie neque. Nunc est lorem, eleifend sit amet ex eu, eleifend fringilla arcu..',
        'products' => [
            [
                'name' => 'ELEMENT 2" LED',
                'img' => $this->getViewFileUrl('images/tech-lighting/tech-product-verse.jpg'),
                'trim_options' => [
                    'Square Flanged & Flangless',
                    'Round Flanged & Flangless',
                ],
                'housing_options' => [
                    'Adjustable and Wall Wash',
                    'Remodel Adjustable and Wall Wash',
                    'Ultra-Shallow Fixed',
                ],
                'attributes' => [
                    'Source' => 'LED',
                    'Source lumens' => '925 - 2475 lm',
                    'Delivered Lumens' => '775 - 2025 lm',
                    'Beamspreads' => '10° - 60°, WW'
                ]
            ]
        ]
    ],
    [
        'name' => 'Traverse',
        'anchor' => 'traverse',
        'blurb' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut suscipit nunc in turpis consequat bibendum. Mauris id aliquam mauris. Ut sit amet urna arcu. Quisque a lorem in risus egestas interdum ac tincidunt nisi Donec semper tellus maximus, porta lacus et, tristique dui. Curabitur at molestie neque. Nunc est lorem, eleifend sit amet ex eu, eleifend fringilla arcu..',
        'products' => [
            [
                'name' => 'ELEMENT 2" LED',
                'img' => $this->getViewFileUrl('images/tech-lighting/tech-product-placeholder.jpg'),
                'trim_options' => [
                    'Square Flanged & Flangless',
                    'Round Flanged & Flangless',
                ],
                'housing_options' => [
                    'Adjustable and Wall Wash',
                    'Remodel Adjustable and Wall Wash',
                    'Ultra-Shallow Fixed',
                ],
                'attributes' => [
                    'Source' => 'LED',
                    'Source lumens' => '925 - 2475 lm',
                    'Delivered Lumens' => '775 - 2025 lm',
                    'Beamspreads' => '10° - 60°, WW'
                ]
            ]
        ]
    ]
]
?>
<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();

/** @var \Magento\Catalog\Helper\Output $_helper */
$_helper = $block->getData('outputHelper');
/** @var \Lyonscg\Catalog\Helper\Data $lcgCatalogHelper */
$lcgCatalogHelper = $this->helper(\Lyonscg\Catalog\Helper\Data::class);
/** @var \Magento\Catalog\Block\Product\ProductList\Toolbar $toolBar */
$toolBar = $block->getChildBlock('toolbar');

$productNum = 1;
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></div></div>
<?php else: ?>
    <?= $toolBar instanceof \Magento\Framework\View\Element\BlockInterface ? $toolBar->setIsBottom(false)->toHtml() : ''?>
    <?= $block->getAdditionalHtml() ?>

    <?php
    $viewMode = 'grid';
    $imageDisplayArea = 'category_page_grid';
    $showDescription = false;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>

    <?php foreach ($mockData as $mockCategory): ?>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <h2 id="<?= $mockCategory['anchor'] ?>"><?= $mockCategory['name'] ?></h2>
        <p><?= $mockCategory['blurb'] ?></p>

        <div class="tech-products-grid">
            <?php foreach ($mockCategory['products'] as $mockProduct): ?>
            <div class="product-tile">
                <div class="col-1">
                    <a class="product-name" href="#"><?= $mockProduct['name'] ?></a>
                    <a href="#"
                       class="product photo product-item-photo"
                       tabindex="-1">
                        <img src="<?= $mockProduct['img'] ?>" alt="<?= $mockProduct['name'] ?>" />
                    </a>
                    <a href="#" class="btn btn-secondary product-overview"><?= __('Product Overview') ?></a>
                </div>
                <div class="col-2 product details product-item-details">
                    <a class="product-name" href="#"><?= $mockProduct['name'] ?></a>

                    <?php if ($mockProduct['trim_options']): ?>
                        <div class="tech-trim-options">
                            <p class="product-attribute-title"><?= __('Trim Options') ?></p>
                            <ul class="product-attribute-list">
                                <?php foreach ($mockProduct['trim_options'] as $trimOption): ?>
                                <li><?= $trimOption ?></li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    <?php endif; ?>

                    <?php if ($mockProduct['housing_options']): ?>
                        <div class="tech-housing-options">
                            <p class="product-attribute-title"><?= __('Housing Options') ?></p>
                            <ul class="product-attribute-list">
                                <?php foreach ($mockProduct['housing_options'] as $housingOption): ?>
                                <li>
                                    <a href="#"><?= $housingOption ?></a>
                                </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    <?php endif; ?>

                    <?php if ($mockProduct['attributes']): ?>
                        <div class="tech-attributes">
                            <dl>
                             <?php foreach ($mockProduct['attributes'] as $key => $value): ?>
                                <dt><?= $key ?></dt>
                                <dd><?= $value ?></dd>
                            <?php endforeach; ?>
                            </dl>
                        </div>
                    <?php endif; ?>

                    <a href="#" class="btn btn-secondary product-overview"><?= __('Product Overview') ?></a>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
    </div>
    <?php endforeach; ?>

<script>
    require([
        'jquery',
    ], function ($) {
        $('body').addClass('page-layout-1column');
    })
</script>

<?php endif; ?>
