<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<?php 
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $currentUrl = $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]);
    if (strpos($currentUrl, 'catalogsearch') == false) {
    $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');
    $catId = $category->getIsArchitechData();
    $archClass = ($catId) ? 'product-filters' : '';
  }
?>
<div class="toolbar-sorter sorter">
  <?php if (strpos($currentUrl, 'catalogsearch') == false) { ?>
  <?php if ($catId) { ?>
    <a href="javascript:void(0);" class="filters-btn" id="filters-btn" onClick="toggeleFilter()" 
    data-mage-init='{"Magento_Catalog/js/show-filters":{}}' style="display:none;">
    <?= $block->escapeHtml(__('Filter By')) ?></a>
  <?php } else { ?>
    <strong class="filters-btn" id="filters-btn" data-mage-init='{"Magento_Catalog/js/show-filters":{}}' style="display:none;"><?= $block->escapeHtml(__('Filter By')) ?></strong>
  <?php } ?>
  <?php } ?>
  <?php if (strpos($currentUrl, 'catalogsearch') == true) { ?>
    <strong class="filters-btn" id="filters-btn" data-mage-init='{"Magento_Catalog/js/show-filters":{}}' style="display:none;"><?= $block->escapeHtml(__('Filter By')) ?></strong>
  <?php } ?>
  
    <label class="sorter-label" for="sorter"><?= $block->escapeHtml(__('Sort By')) ?></label>
    <select id="sorter" data-role="sorter" class="sorter-options">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order) :?>
            <option value="<?= $block->escapeHtmlAttr($_key) ?>"
                <?php if ($block->isOrderCurrent($_key)) :?>
                    selected="selected"
                <?php endif; ?>
                >
                <?= $block->escapeHtml(__($_order)) ?>
            </option>
        <?php endforeach; ?>
    </select>
    <?php if ($block->getCurrentDirection() == 'desc') :?>
        <a title="<?= $block->escapeHtmlAttr(__('Set Ascending Direction')) ?>"
           href="#"
           class="action sorter-action sort-desc"
           data-role="direction-switcher"
           data-value="asc">
            <span><?= $block->escapeHtml(__('Set Ascending Direction')) ?></span>
        </a>
    <?php else :?>
        <a title="<?= $block->escapeHtmlAttr(__('Set Descending Direction')) ?>"
           href="#"
           class="action sorter-action sort-asc"
           data-role="direction-switcher"
           data-value="desc">
            <span><?= $block->escapeHtml(__('Set Descending Direction')) ?></span>
        </a>
    <?php endif; ?>
</div>

<?php if (strpos($currentUrl, 'catalogsearch') == false) { ?>
<?php if ($catId) { ?>
    <script>
        function toggeleFilter() {
            var x = document.getElementById("narrow-by-list");
            if (x.style.display === "block") {
                x.style.display = "none";
            } else {
                x.style.display = "block";
            }
        }
    </script>
<?php } ?>
<?php } ?>
