<?php
    /** @var $block \Capgemini\LightBulbs\Block\Upsell */
    use Magento\Framework\App\Action\Action;

    /** @var \Magento\Catalog\Helper\Output $_helper */
    $_helper = $this->helper(Magento\Catalog\Helper\Output::class);
    /** @var  \Capgemini\CustomHeight\Helper\PriceHeight $customHeightHelper */
    $customHeightHelper = $this->helper(Capgemini\CustomHeight\Helper\PriceHeight::class);
    /** @var \Lyonscg\Catalog\Helper\Data $lcgCatalogHelper */
    $lcgCatalogHelper = $this->helper(\Lyonscg\Catalog\Helper\Data::class);
    $_products = $block->getProducts();
    /** @var \Magento\Quote\Model\Quote\Item $_item */
    $_item = $block->getLastOrderedItem();
    $customHeightValue = $_item->getExtensionAttributes()->getCustomHeightValue() ?? $_item->getCustomHeightValue();
    $usedSimpleProduct = $block->getSimpleProductFromQuoteItem($_item);
    $usedSimpleProductId = $usedSimpleProduct ? $usedSimpleProduct->getId() : null;
?>

    <?php /* <div id="lightbulb-upsell-modal-content" data-bind="scope:'lightbulbUpsell'"> */ ?>
    <div class="lightbulb-header">
        <strong>Item Added to Cart</strong>
        <a class="lightbulb-cart-link" href="<?= $block->getCartUrl(); ?>">View My Cart</a>
    </div>
    <div class="item-added modal-row">
        <div class="modal-column-left">
            <?php $productImage = $block->getProductImage($lcgCatalogHelper->getChildProduct($_item->getProduct())); ?>
            <div class="product photo product-item-photo">
                <?= $productImage->toHtml() ?>
            </div>
        </div>
        <div class="modal-column-right">
            <strong class="product name product-item-name">
                <span><?= $block->escapeHtml($_item->getName()) ?></span>
            </strong>
            <?php if(!empty($customHeightValue)) : ?>
                <div class="product-item-details">
                    <dl class="item-options">
                        <dt class="ch">Custom Height</dt>
                        <dt class="ch"><?= $customHeightValue ?>"</dt>
                        <dt class="ch"><?= $customHeightHelper->getAvailabilityMessage() ?></dt>
                    </dl>
                </div>
            <?php endif; ?>
            <div class="product-info-price">
                <span>Qty: <?= $_item->getQtyToAdd() ?></span>
                <?= $block->getItemPrice($_item) ?>
            </div>
        </div>
    </div>
<?php if (!empty($_products) && isset($_products[$usedSimpleProductId])) : ?>
    <hr />
    <ol class="products list items product-items">
        <li class="accessories">Would you like bulbs with that?</li>
        <?php foreach ($_products[$usedSimpleProductId] as $_product): ?>
            <?php $qty = $block->getProductQty($_product) * $_item->getQtyToAdd(); ?>
            <li class="item product product-item modal-row">
                <div class="modal-column-left">
                    <?php $productImage = $block->getProductImage($_product); ?>
                    <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                       class="product photo product-item-photo"
                       tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>

                </div>
                <div class="modal-column-right">
                    <strong class="product name product-item-name">
                        <a class="product-item-link"
                           href="<?= $block->escapeUrl($_product->getProductUrl()) ?>">
                            <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                        </a>
                    </strong>
                    <div class="product-info-price">
                        <span>Qty: <?= $qty ?></span>
                        <br>
                        <span><?= $block->getProductPriceMultipleTo($_product, $_item->getQtyToAdd()) ?></span>
                    </div>
                    <div class="lightbulb-form-container">
                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                        <form data-role="tocart-form"
                              data-product-sku="<?= $block->escapeHtmlAttr($_product->getSku()) ?>"
                              action="<?= $block->escapeUrl($postParams['action']) ?>"
                              method="post">
                            <input type="hidden"
                                   name="product"
                                   value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                            <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                   value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                            <input type="hidden" name="qty" value="<?= $qty ?>">
                            <?= $block->getFormkey(); ?>
                            <button type="submit"
                                    title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                    class="action tocart primary">
                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                            </button>
                        </form>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
    </ol>
<?php endif; ?>
