<?php /* */ ?>
<div id="lightbulb-upsell-modal" style="display: none;">
    <div id="lightbulb-upsell-modal-content" class="products wrapper">

    </div>
</div>
<script type="text/x-magento-init">
    {
        "#lightbulb-upsell-modal": {
            "lightbulbModal": {}
        }
    }
</script>
<?php /* */?>
<style>
    .catalog-product-view .modal-header .action-close {
        width: 15px;
    }
    #lightbulb-upsell-modal .modal-row {
        clear: both;
        overflow: hidden;
    }
    #lightbulb-upsell-modal .lightbulb-header {
        margin-bottom: 2rem;
    }
    #lightbulb-upsell-modal .lightbulb-header strong {
        font-size: 2.25rem;
    }
    #lightbulb-upsell-modal .lightbulb-header a {
        padding-left: 1rem;
    }
    #lightbulb-upsell-modal li {
        margin-bottom: 1rem;
    }
    #lightbulb-upsell-modal .lightbulb-accessories-title {
        text-transform: capitalize;
    }
    #lightbulb-upsell-modal .modal-column-left {
        float: left;
        width: 30%;
    }
    #lightbulb-upsell-modal .modal-column-right {
        float: left;
        width: 70%;
    }
    #lightbulb-upsell-modal .product.name.product-item-name {
        font-size: 1.6rem;
        margin-bottom: 2rem;
    }
    #lightbulb-upsell-modal .item-added .product.name.product-item-name {
        font-size: 2rem;
    }
    #lightbulb-upsell-modal .product-items .product-info-price {
        margin-bottom: 1rem;
    }
    #lightbulb-upsell-modal .product-info-price .qty {
        float: left;
        text-transform: capitalize;
    }
    #lightbulb-upsell-modal .product-info-price .price {
        float: right;
    }
    #lightbulb-upsell-modal .item-added .product-info-price .qty {
        display: block;
        float: none;
        margin-bottom: 1rem;
    }
    #lightbulb-upsell-modal .item-added .product-info-price .price{
        display: block;
        float: none;
    }
    #lightbulb-upsell-modal .action.tocart.primary {
        width: 220px;
    }
</style>
