<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<input type="checkbox" class="checkbox product-item-checkbox" id="checkbox-item[<?= /* @noEscape */ $block->getItem()->getId()*1 ?>]" name="selected[<?= /* @noEscape */ $block->getItem()->getId()*1 ?>]" data-role="select-product" />
<label class="product-label-checkbox" for="checkbox-item[<?= /* @noEscape */ $block->getItem()->getId()*1 ?>]"></label>