<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<form class="form form-orders-search"
      id="oar-widget-orders-and-returns-form"
      data-mage-init='{"ordersReturns":{}, "validation":{}}'
      action="<?= $block->escapeUrl($block->getActionUrl()) ?>"
      method="post" name="guest_post">
    <input type="hidden" name="oar_type" id="quick-search-type-id" value="zip" />
    <fieldset class="fieldset">
        <div class="field note no-label"><?= $block->escapeHtml(__('Enter your Order ID and Billing Zip Code to check your current order status.')) ?></a></div>

        <div class="field id required">
            <label class="label" for="oar-order-id"><span><?= $block->escapeHtml(__('Order ID Number')) ?></span></label>

            <div class="control">
                <input type="text" class="input-text" id="oar-order-id" name="oar_order_id"
                       data-validate="{required:true}"/>
            </div>
        </div>

        <div id="oar-zip" class="field zip required">
            <label class="label" for="oar_zip"><span><?= $block->escapeHtml(__('Billing ZIP Code')) ?></span></label>

            <div class="control">
                <input type="text" class="input-text" id="oar_zip" name="oar_zip" data-validate="{required:true}"/>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Continue')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Continue')) ?></span>
            </button>
        </div>
    </div>
</form>
