<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */

$toolbar = $block->getLayout()->getBlock('product_list_toolbar');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$currentUrl = $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]);
if (strpos($currentUrl, 'catalogsearch') == false) {
    $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');
    $catId = $category->getIsArchitechData();
}
?>

<?php if ($block->canShowBlock()) : ?>
    <?php if (strpos($currentUrl, 'catalogsearch') == false) { ?>
    <?php if ($catId) { ?>
    <div class="block filter product-filters" id="layered-filter-block" data-mage-init='
    {
        "collapsible":
        {
            "openedState": "active",
            "collapsible": true,
            "active": false,
            "collateral":
            {
                "openedState": "filter-active",
                "element": "body"
            }
        }
    }'>
    <?php } else { ?>
    <div class="block filter" id="layered-filter-block" data-mage-init='
    {
        "collapsible":
        {
            "openedState": "active",
            "collapsible": true,
            "active": false,
            "collateral":
            {
                "openedState": "filter-active",
                "element": "body"
            }
        }
    }'>
    <?php } ?>
    <?php } ?>
    <?php if (strpos($currentUrl, 'catalogsearch') == true) { ?>
    <div class="block filter" id="layered-filter-block" data-mage-init='
    {
        "collapsible":
        {
            "openedState": "active",
            "collapsible": true,
            "active": false,
            "collateral":
            {
                "openedState": "filter-active",
                "element": "body"
            }
        }
    }'>
<?php } ?>
        <?php $filtered = count($block->getLayer()->getState()->getFilters()) ?>
        <div class="block-title filter-title" data-count="<?= /* @noEscape */ $filtered ?>">
            <strong data-role="title"><?= $block->escapeHtml(__('Shop By')); ?></strong>
        </div>
        <div class="block-content filter-content">
            <div class="block-selected-filters">
                <div class="selected-filters-inner">
                    <?= $block->getChildHtml('state') ?>

                    <?php if ($block->getLayer()->getState()->getFilters()) : ?>
                        <div class="block-actions filter-actions">
                            <a href="<?= $block->escapeUrl($block->getClearUrl()) ?>" class="action clear filter-clear">
                                <span><?= $block->escapeHtml(__('Clear All')) ?></span>
                            </a>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
            <?php $wrapOptions = false; ?>
            <div class="block-filters-wrapper">
                <?php foreach ($block->getFilters() as $filter) : ?>
                    <?php if ($filter->getItemsCount()) : ?>
                        <?php if (!$wrapOptions) : ?>
                            <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?= $block->escapeHtml(__('Filter By')) ?></strong>
                            <div class="filter-options" id="narrow-by-list" data-role="content" data-mage-init='
                            {
                                "accordion":
                                {
                                    "openedState": "active",
                                    "collapsible": true,
                                    "active": false,
                                    "multipleCollapsible": false
                                }
                            }'>
                    <?php $wrapOptions = true;
                    endif; ?>
                    <div data-role="collapsible" class="filter-options-item">
                        <div data-role="title" class="filter-options-title"><?= $block->escapeHtml(__($filter->getName())) ?></div>
                        <div data-role="content" class="filter-options-content"><?= /* @noEscape */ $block->getChildBlock('renderer')->render($filter) ?></div>
                    </div>
                    <?php endif; ?>
                    <?php endforeach; ?>
                    <?php if ($wrapOptions) : ?>
                </div>
            <?php else : ?>
                <script>
                    require([
                        'jquery'
                    ], function ($) {
                        $('#layered-filter-block').addClass('filter-no-options');
                    });
                </script>
                <?php endif; ?>
                <?php if ($toolbar instanceof \Magento\Framework\View\Element\BlockInterface) : ?>
                    <?=  $toolbar->setIsBottom(false)->toHtml() ?>
                <?php else : ?>
                    <?php $block->getLayer()->getProductCollection()->load() ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
<?php elseif ($toolbar instanceof \Magento\Catalog\Block\Product\ProductList\Toolbar) : ?>
    <?php $toolbar->getCollection()->count(); ?>
<?php else : ?>
    <?php $block->getLayer()->getProductCollection()->load() ?>
<?php endif; ?>


<?php if (strpos($currentUrl, 'catalogsearch') == false) { ?>
<?php if ($catId) { ?>
<script>
    require([
        'jquery',
    ], function ($) {
        $(document).on('contentUpdated', function () {
            location.reload(true);
        });
    })
</script>
<?php } ?>
<?php } ?>
