<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<button type="button" title="<?= $block->escapeHtmlAttr(__('Delete This Project')) ?>" data-wishlist-delete='{"wishlistId":"<?= $block->escapeHtmlAttr($block->getWishlistInstance()->getId()) ?>", "redirectUrl":"<?= $block->escapeUrl($block->getRedirectUrl()) ?>", "deleteUrl":"<?= $block->escapeUrl($block->getDeleteUrl()) ?>"}' class="action btn btn-secondary remove"><span><?= $block->escapeHtmlAttr(__('Delete This Project')) ?></span></button>
