<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\View\Element\Template;
use Magento\Vault\Api\Data\PaymentTokenInterface;
use Magento\Vault\Block\CardRendererInterface;

/** @var CardRendererInterface|Template $block
 * @var \Magento\Framework\Escaper $escaper */
$ccNumberView = $block->escapeHtml($block->getNumberLast4Digits());
?>

<!--TODO: Add CC Type/Name-->
<div class="method-cc-name">
    <span><?= $escaper->escapeHtml(__('CC Name')) ?></span>
</div>
<div class="method-cc-name">
    <span><?= $escaper->escapeHtml(__('CC Type')) ?></span>
</div>

<div class="method-card-img">
    <img src="<?= /* @noEscape */ $block->getIconUrl() ?>"
         width="<?= /* @noEscape */ $block->getIconWidth() ?>"
         height="<?= /* @noEscape */ $block->getIconHeight() ?>"
    />
</div>

<div class="method-info">
    <div>
        <span><?= $escaper->escapeHtml(__('**** **** ****')) ?></span>
        <span><?= /* @noEscape */ $ccNumberView ?></span>
    </div>
    <div>
        <span><?= $escaper->escapeHtml(__('Exp Date: ')) ?></span>
        <span><?= $escaper->escapeHtml($block->getExpDate()) ?></span>
    </div>

    <form class="form"
          action="<?= $escaper->escapeUrl($block->getUrl('vault/cards/deleteaction')) ?>"
          method="post">
        <?= $block->getBlockHtml('formkey') ?>
        <input name="<?= /* @noEscape */ PaymentTokenInterface::PUBLIC_HASH ?>"
               value="<?= /* @noEscape */ $block->getToken()->getPublicHash() ?>"
               type="hidden"/>

        <button type="submit"
                class="action delete"
                data-mage-init='{
                                    "Magento_Vault/js/customer_account/deleteWidget":{
                                        "type": "popup",
                                        "modalClass": "my-credit-cards-popup",
                                        "toggleEvent": "click",
                                        "title": "<?= $escaper->escapeHtml(__('Remove')) ?>",
                                        "content": "<?= $escaper->escapeHtml(__('Are you sure you want to delete this card: %1?', $ccNumberView)) ?>"
                                    }
                                }'>
            <span><?= $escaper->escapeHtml(__('Remove')) ?></span>
        </button>
    </form>
</div>





