<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

//use Capgemini\BloomreachThematic\Model\TechnicalProduct;
//use Magento\Framework\App\Action\Action;

?>
<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>

<?php

//$_productCollection = $block->getLoadedProductCollection();
//$_productCollection->setOrder('product_sort_order', 'asc');
//echo get_class($block);
//count($_productCollection);
//exit('hello');

?>

<?php
// Category collection file code start here

/*
    $current_category = $this->frameworkRegistry->registry('current_category');
    $modelCollection = \Magento\Framework\App\ObjectManager::getInstance()->create(\Rysun\ArchiCollection\Model\ArchiCollection::class);
    $collection = $modelCollection->getCollection();
    $collection->addFieldToFilter('category_id',$current_category->getId());


    //$collection = $block->getCollectionName();
    $_helper    = $this->helper(Magento\Catalog\Helper\Output::class);
    $_category  = $block->getCurrentCategory();
    $imageHelper = \Magento\Framework\App\ObjectManager::getInstance()->get(\Magento\Catalog\Helper\Image::class);
    $image = $imageHelper->getDefaultPlaceholderUrl('image');
    
    
    echo '<div class="product-subcategory-view"><div class="d-grid product-category-grid">';
        foreach ($collection as $collection_label) {

            $_imgUrl = ($collection_label->getThumbnailImage()) ?  $collection_label->getThumbnailImage() : $image;

            echo '<div class="subcategory-grid-box">
                    <a href="#'.$collection_label->getWebName().'" class="d-flex align-items-center justify-content-center product-category-grid-box">'.
                        '<div class="h6 me-auto">' . $collection_label->getWebName() . '</div>'.
                        '<img src="'.$block->escapeUrl($_imgUrl).'" alt="'.$collection_label->getWebName().'" width="148" height="125" />'.
                    '</a>'.
                '</div>';
        }
    echo '</div></div>';

    // Category collection file code start here


*/
?>


<?php

//category list - platform code ends here

$attributeData = [];
$attributeLabel = [];
    $current_category = $this->frameworkRegistry->registry('current_category');    
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();

    $categories[] = $current_category->getId();

    //product collection 

    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    /** @var \Magento\Catalog\Model\ResourceModel\Product\Collection $productCollection */
    $prodCollection = $objectManager->create('Magento\Catalog\Model\ResourceModel\Product\Collection');
    /** Apply filters here */
    $_productCollection = $prodCollection->addAttributeToSelect('*')
                ->addCategoriesFilter(['in' => $categories])           
                ->setOrder('product_sort_order', 'asc')
                ->load();

    $productCollectionFactory = $objectManager->create('Rysun\ArchiCollection\Model\ArchiCollection');
    $collection = $productCollectionFactory->getCollection();
    $collection->addFieldToFilter('category_id',$current_category->getId());
    $collection->setOrder('sort_order','ASC');


?>
<div class="products-grid custom-products">
    <div class="products-sep"></div>
    <?php 
        foreach($collection as $collectionlist){
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $platformCollectionFactory = $objectManager->create('Rysun\ArchiCollection\Model\ArchiPlatform');
            $platformCollection = $platformCollectionFactory->getCollection();
            $platformCollection->addFieldToFilter('category_id',$current_category->getId());
            $platformCollection->addFieldToFilter('collection_id',$collectionlist->getId());
            $platformCollection->setOrder('sort_order','ASC');

    ?> 
    <?php //echo ' platform id'.print_r($platformCollection->getAllIds());
        $platformAllIds = implode(',',$platformCollection->getAllIds());

        $productUpdatedIDs = implode(',',$_productCollection->getAllIds());
        // print_r($productUpdatedIDs);
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        /** @var \Magento\Catalog\Model\ResourceModel\Product\Collection $productCollection */
        $productDataCollection = $objectManager->create('Magento\Catalog\Model\ResourceModel\Product\Collection');
        /** Apply filters here */
        $prodDatacollection = $productDataCollection->addAttributeToSelect('*');
        $prodDatacollection->addAttributeToFilter(
            'collection_id',array("eq"=>$collectionlist->getSqlServId())
        )
        ->addAttributeToFilter(
            'platform_id',array("in"=>$platformAllIds)
        )
        ->addFieldToFilter('entity_id', array('in' => $productUpdatedIDs))
                    ->load();

            
                    if(count($prodDatacollection) < 1){
                        continue;
                    }

                        
    ?>
        <h2 id="<?= $collectionlist->getWebName()?>"> <?= $collectionlist->getWebName() ?> </h2>
        <h5><?= $collectionlist->getCollectionDescSecond() ?> </h5>
        <p><?= $collectionlist->getCollectionDesc() ?> </p>
        <div class="products list items product-items">
            <div class="item product product-item product-promotion">
                <div class="promotion-content">
                    <a href="javascript:void(0);" class="product photo product-item-photo">
                        <img src="<?= $this->getViewFileUrl('Magento_Catalog::images/placeholder.png'); ?>" width="381" height="511" />
                    </a>
                    <!-- <div class="promotion-content-inner">
                        <h2>LEARN MORE ABOUT <strong><?= $collectionlist->getWebName(); ?></strong> RECESSED PLATFORMS</h2>
                        <p>Features, Benefits, Accessories, Controls. Installation, and More</p>
                        <a href="javascript:void(0);">Start your journey now ></a>
                    </div> -->
                </div>
            </div>
            <?php 
            foreach($platformCollection as $platformlist) {

                    //echo  "before:- ".count($_productCollection);

                //print_r($_productCollection->getAllIds());
                $productUpdatedIDs = implode(',',$_productCollection->getAllIds());
                // print_r($productUpdatedIDs);
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                /** @var \Magento\Catalog\Model\ResourceModel\Product\Collection $productCollection */
                $productDataCollection = $objectManager->create('Magento\Catalog\Model\ResourceModel\Product\Collection');
                /** Apply filters here */
                $prodDatacollection = $productDataCollection->addAttributeToSelect('*');
                $prodDatacollection->addAttributeToFilter(
                    'collection_id',array("eq"=>$collectionlist->getSqlServId())
                )
                ->addAttributeToFilter(
                    'platform_id',array("eq"=>$platformlist->getSqlServId())
                )
                ->addFieldToFilter('entity_id', array('in' => $productUpdatedIDs))
                ->setOrder('product_sort_order','ASC')
                            ->load();

                if(count($prodDatacollection) < 1){
                    continue;
                }

                //Render Product collection

                $productList =  $deliveredLumens = $bining= $beamSpread = $housing = $dimming =$ratingCertification = [];

                $finalArrayValues = [];
                foreach($prodDatacollection as $key =>  $item) {

                   // echo '<pre>';
                   // print_r($item->getData());
                   // echo $item->getProductUrl();
                   // exit('coming here');
                    $productData = [];
                    //List for printing Product List
                    $productData['name'] = $item->getName(); 
                    $productData['url'] = $item->getProductUrl(); 
                    $productData['sort'] = $item->getProductSortOrder(); 
                    $productList[] = $productData;



                     //WORKING CODE START
                     $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                     $specificationCollection = $objectManager->create('Rysun\SpecificationAttribute\Model\SpecificationAttribute');
                     $specificationCol = $specificationCollection->getCollection();
                     $specificationCol->addFieldToFilter('category_id',$current_category->getId());
                     $specificationCol->addFieldToFilter('collection_id',$collectionlist->getSqlServId());
                     //$specificationCol->setOrder('sort_order','ASC');

                     //echo count($specificationCol); 
                     
                     foreach($specificationCol as $specificationDetail){
                         $deliveredLumens = [];
                         //echo '<pre>';
                         //print_r($specificationDetail->getData('attribute_code'));
                         //echo '</pre>';
                         $attributeCode = $specificationDetail->getData('attribute_code');
                         if($attributeCode == 'minimum_delivered_lumens_arch_filter' || $attributeCode == 'maximum_delivered_lumens_arch_filter'){
                            continue;
                         }
                         $productValue = $item->getAttributeText($attributeCode);
                         //echo '<pre>';
                         //print_r($productValue);
                         //echo '</pre>';
                         //$productAttrLabel = $item->getAttribute($attributeCode);

                         if(is_array($productValue)){
                             foreach($productValue  as $value){
                                 $deliveredLumens[] = $value;
                                 $attributeData[$attributeCode][] =  $value;

                             }
                         } else {
                             $deliveredLumens[] = $productValue ;
                             $attributeData[$attributeCode][] = $productValue ;
                         }
                         //$deliveredString  = implode(", ", $deliveredLumens); 
                         //$deliveredString  =  $deliveredLumens;

                         //if(empty($deliveredString)){
                          //   continue;
                         //}
                         //echo 'coming here';
                         //echo '<pre>';  
                         //print_r($item->getResource()->getAttribute($attributeCode)->getStoreLabel());
                         //print_r($deliveredString);
                         //echo '</pre>';
                         $attributeLabel[$attributeCode][] = $item->getResource()->getAttribute($attributeCode)->getStoreLabel();
                         ?>
                         <?php 
                        // echo '<pre>';
                         //print_r($attributeLabel);
                         //print_r($deliveredString);
                         //echo '</pre>';

                        // $attributeData[$attributeCode]['label'] = $item->getResource()->getAttribute($attributeCode)->getStoreLabel();
                         //$attributeData[$attributeCode]['data'][] = $deliveredString;
                         ?>
                         <?php //echo $attributeLabel; ?>       
                         <?php //echo $deliveredString;?>
                         <?php
                         //exit;
                     }
                     //echo '<pre>';
                     //print_r(array_unique($attributeData['data']));
                    // print_r($attributeData);
                    // print_r($attributeLabel); //exit;

                    
                    // print_r($finalArrayValues);
                    //  $newArray = [];
                    //  foreach($attributeData as $key => $listItem){
                    //     $newAraay[$key]['label'] = $listItem['label']; 
                    //         foreach($listItem['data'] as $newItem){
                    //             $newthing = $newAraay[$key]['data'];
                    //             $newAraay[$key]['test'][] = array_merge($newthing,explode(',',$newItem));
                    //         }
                    //     //$newAraay[$key]['data'] = array_unique($listItem['data']); 
                    //  }
                    //  print_r('new array');
                    //  print_r($newAraay);
                     //exit;
                     //WORKING CODE START 


                    //$deliveredLumens[] = $item->getData('maximum_delivered_lumens_filter');
                    //$deliveredLumens[] = $item->getAttributeText('maximum_delivered_lumens_filter');

                    if(is_array($item->getAttributeText('maximum_delivered_lumens_arch_filter'))){
                        $values = $item->getAttributeText('maximum_delivered_lumens_arch_filter');
                        foreach($values  as $value){
                            $deliveredLumens[] = $value;
                        }
                      
                    } else {
                        if(!empty($item->getAttributeText('maximum_delivered_lumens_arch_filter'))){
                        $deliveredLumens[] = $item->getAttributeText('maximum_delivered_lumens_arch_filter');
                        }
                    }

                    //$isAttributeExist = $product->getResource()->getAttribute($attributeCode); 
                    //$optionText = '';
                    //if ($isAttributeExist && $isAttributeExist->usesSource()) {
                    //    $optionText = $isAttributeExist->getSource()->getOptionText($optionId);
                    //}
                    
                    //$bining[] = $item->getData('dimming_arch_filter');
                    //$bining[] = $item->getAttributeText('dimming_arch_filter');
                    if(is_array($item->getAttributeText('color_consistency_sdcm_binning_arch_filter'))){
                        $values = $item->getAttributeText('color_consistency_sdcm_binning_arch_filter');
                        foreach($values  as $value){
                            if(!empty($value)){
                                $bining[] = $value;
                            }
                           
                        }
                      
                    } else {
                        if(!empty($item->getAttributeText('color_consistency_sdcm_binning_arch_filter'))){
                            $bining[] = $item->getAttributeText('color_consistency_sdcm_binning_arch_filter');
                        }
                        
                    }


                    //$beamSpread[] = $item->getData('beam_spread_arch_option');

                    if(is_array($item->getAttributeText('beam_spread_arch_option'))){
                        $values = $item->getAttributeText('beam_spread_arch_option');
                        foreach($values  as $value){
                            if(!empty($value)){
                            $beamSpread[] = $value;
                            }
                        }
                      
                    } else {
                        if(!empty($item->getAttributeText('beam_spread_arch_option'))){
                            $beamSpread[] = $item->getAttributeText('beam_spread_arch_option');
                        }
                    }
                    
                    //$housing[] = $item->getData('housing_type_filter');
                    //$housing[] = $item->getAttributeText('housing_type_filter');

                    if(is_array($item->getAttributeText('housing_type_arch_filter'))){
                        $values = $item->getAttributeText('housing_type_arch_filter');
                        foreach($values  as $value){
                            if(!empty($value)){
                            $housing[] = $value;
                            }
                        }
                      
                    } else {
                        if(!empty($item->getAttributeText('housing_type_arch_filter'))){
                            $housing[] = $item->getAttributeText('housing_type_arch_filter');
                        }
                    }


                    //$dimming[] = $item->getData('dimming_arch_filter');
                    //$dimming[] = $item->getAttributeText('dimming_arch_filter');
                    if(is_array($item->getAttributeText('dimming_type_arch_filter'))){
                        $values = $item->getAttributeText('dimming_type_arch_filter');
                        foreach($values  as $value){
                            if(!empty($value)){
                            $dimming[] = $value;
                            }
                        }
                      
                    } else {
                        if(!empty($item->getAttributeText('dimming_type_arch_filter'))){
                         $dimming[] = $item->getAttributeText('dimming_type_arch_filter');
                        }
                    }
                    //$ratingCertification[] = $item->getData('maximum_delivered_lumens_filter');
                    //$ratingCertification[] = $item->getAttributeText('maximum_delivered_lumens_filter');
                    if(is_array($item->getAttributeText('rating_certification_arch_filter'))){
                        $values = $item->getAttributeText('rating_certification_arch_filter');
                        foreach($values  as $value){
                            if(!empty($value)){
                            $ratingCertification[] = $value;
                            }
                        }
                      
                    } else {
                        if(!empty($item->getAttributeText('rating_certification_arch_filter'))){
                        $ratingCertification[] = $item->getAttributeText('rating_certification_arch_filter');
                        }
                    }


                }

                foreach($attributeData as $keyIndex => $keyItem){
                    $newArray = [];
                    $newArray['label'] = $attributeLabel[$keyIndex][0];
                    $newArray['data'] = array_unique($keyItem);
                    $finalArrayValues[] = $newArray;
                 }


                //array_unique($deliveredLumens); = $bining= $beamSpread = $housing = $dimming =$ratingCertification = [];

                //echo '<pre>';
                //print_r($productList);
                //echo '</pre>';
                //exit('coming here');

            ?>

                <?php 
                //echo '<pre>';
                //print_r($attributeData);
                
                
                ?>
                <div class="item product product-item">
                    <div class="product-item-info">
                        <a href="javascript:void(0);" class="product photo product-item-photo">
                            <img src="<?= $this->getViewFileUrl('Magento_Catalog::images/placeholder.png') ?>" width="240" height="300" />
                        </a>
                        <div class="d-flex product-item-thumb">
                            <a href="javascript:void(0);">
                                <img src="<?= $this->getViewFileUrl('Magento_Catalog::images/placeholder.png') ?>" width="50" height="50" />
                            </a>
                            <a href="javascript:void(0);">
                                <img src="<?= $this->getViewFileUrl('Magento_Catalog::images/placeholder.png') ?>" width="50" height="50" />
                            </a>
                            <a href="javascript:void(0);">
                                <img src="<?= $this->getViewFileUrl('Magento_Catalog::images/placeholder.png') ?>" width="50" height="50" />
                            </a>
                            <a href="javascript:void(0);">
                                <img src="<?= $this->getViewFileUrl('Magento_Catalog::images/placeholder.png') ?>" width="50" height="50" />
                            </a>
                            <a href="javascript:void(0);">
                                <img src="<?= $this->getViewFileUrl('Magento_Catalog::images/placeholder.png') ?>" width="50" height="50" />
                            </a>
                        </div>
                        <div class="product details product-item-details">
                            <div class="product name product-item-name">
                                <a class="product-item-link" href="javascript:void(0);">
                                    <?= $platformlist->getWebName(); ?>
                                </a>
                            </div>
                            <div class="product-attribute-head">Specifications</div>
                          
                            <?php 

                            
                            foreach($finalArrayValues as $specificationData){

                            ?>
                                <div class="spec-inline">
                                    <ul class="product-attribute-list">
                                        <span><?php echo $specificationData['label']; ?></span>
                                        <!--<li>850 - 1500</li>-->
                                        <li>
                                        <?php echo  implode(',',$specificationData['data']);                                
                                        ?></li>
                                    </ul>
                                </div>
                            <?php

                            }
                            ?>

                            <?php if(!empty($productList)) { ?>
                            <div class="product-attribute-head">Products</div>
                            <div class="tech-attributes">
                                <ul class="product-attribute-list">
                                    <?php         
                                        foreach($productList as $item) {
                                    ?>
                                        <li><a href="<?= $item['url'] ?>"><?= $item['name']; ?></a></li>
                                    <?php } ?>
                                </ul>
                            <?php } ?>                    
                            </div>
                        </div>
                    </div>
                </div>
            <?php  } ?>
        </div>
    <?php  } ?>
</div>


<?php /*
<script>
    require([
        'jquery',
        'owlcarousel'
    ],function($) {
        $(document).ready(function(){
            $('.product-item-thumb').owlCarousel({
                nav : true,
                dots: false,
                autoPlay: false,
                margin: 10,
                items : 5
            });
        });
    })
</script>
*/ ?>