<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

//use Capgemini\BloomreachThematic\Model\TechnicalProduct;
//use Magento\Framework\App\Action\Action;

?>
<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>

<?php

$_productCollection = $block->getLoadedProductCollection();
//echo get_class($block);
//exit('hello');

?>

<?php
// Category collection file code start here

/*
    $current_category = $this->frameworkRegistry->registry('current_category');
    $modelCollection = \Magento\Framework\App\ObjectManager::getInstance()->create(\Rysun\ArchiCollection\Model\ArchiCollection::class);
    $collection = $modelCollection->getCollection();
    $collection->addFieldToFilter('category_id',$current_category->getId());


    //$collection = $block->getCollectionName();
    $_helper    = $this->helper(Magento\Catalog\Helper\Output::class);
    $_category  = $block->getCurrentCategory();
    $imageHelper = \Magento\Framework\App\ObjectManager::getInstance()->get(\Magento\Catalog\Helper\Image::class);
    $image = $imageHelper->getDefaultPlaceholderUrl('image');
    
    
    echo '<div class="product-subcategory-view"><div class="d-grid product-category-grid">';
        foreach ($collection as $collection_label) {

            $_imgUrl = ($collection_label->getThumbnailImage()) ?  $collection_label->getThumbnailImage() : $image;

            echo '<div class="subcategory-grid-box">
                    <a href="#'.$collection_label->getWebName().'" class="d-flex align-items-center justify-content-center product-category-grid-box">'.
                        '<div class="h6 me-auto">' . $collection_label->getWebName() . '</div>'.
                        '<img src="'.$block->escapeUrl($_imgUrl).'" alt="'.$collection_label->getWebName().'" width="148" height="125" />'.
                    '</a>'.
                '</div>';
        }
    echo '</div></div>';

    // Category collection file code start here


*/
?>


<?php

//category list - platform code ends here


    $current_category = $this->frameworkRegistry->registry('current_category');    
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();

    $productCollectionFactory = $objectManager->create('Rysun\ArchiCollection\Model\ArchiCollection');
    $collection = $productCollectionFactory->getCollection();
    $collection->addFieldToFilter('category_id',$current_category->getId());
    $collection->setOrder('sort_order','ASC');




?>
<div class="products-grid custom-products">
    <div class="products-sep"></div>
    <?php 
        foreach($collection as $collectionlist){
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $platformCollectionFactory = $objectManager->create('Rysun\ArchiCollection\Model\ArchiPlatform');
            $platformCollection = $platformCollectionFactory->getCollection();
            $platformCollection->addFieldToFilter('category_id',$current_category->getId());
            $platformCollection->addFieldToFilter('collection_id',$collectionlist->getId());
            $platformCollection->setOrder('sort_order','ASC');

    ?> 
    <?php //echo ' platform id'.print_r($platformCollection->getAllIds());
        $platformAllIds = implode(',',$platformCollection->getAllIds());

        $productUpdatedIDs = implode(',',$_productCollection->getAllIds());
        // print_r($productUpdatedIDs);
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        /** @var \Magento\Catalog\Model\ResourceModel\Product\Collection $productCollection */
        $productDataCollection = $objectManager->create('Magento\Catalog\Model\ResourceModel\Product\Collection');
        /** Apply filters here */
        $prodDatacollection = $productDataCollection->addAttributeToSelect('*');
        $prodDatacollection->addAttributeToFilter(
            'collection_id',array("eq"=>$collectionlist->getSqlServId())
        )
        ->addAttributeToFilter(
            'platform_id',array("in"=>$platformAllIds)
        )
        ->addFieldToFilter('entity_id', array('in' => $productUpdatedIDs))
                    ->load();
                    if(count($prodDatacollection) < 1){
                        continue;
                    }

    ?>
        <h2 id="<?= $collectionlist->getWebName()?>"> <?= $collectionlist->getWebName() ?> </h2>
        <h5><?= $collectionlist->getCollectionDescSecond() ?> </h5>
        <p><?= $collectionlist->getCollectionDesc() ?> </p>
        <div class="products list items product-items">
            <div class="item product product-item product-promotion">
                <div class="promotion-content">
                    <a href="javascript:void(0);" class="product photo product-item-photo">
                        <img src="<?= $this->getViewFileUrl('Magento_Catalog::images/placeholder.png'); ?>" width="381" height="511" />
                    </a>
                    <!-- <div class="promotion-content-inner">
                        <h2>LEARN MORE ABOUT <strong><?= $collectionlist->getWebName(); ?></strong> RECESSED PLATFORMS</h2>
                        <p>Features, Benefits, Accessories, Controls. Installation, and More</p>
                        <a href="javascript:void(0);">Start your journey now ></a>
                    </div> -->
                </div>
            </div>
            <?php 
            foreach($platformCollection as $platformlist) {

                    //echo  "before:- ".count($_productCollection);

                //print_r($_productCollection->getAllIds());
                $productUpdatedIDs = implode(',',$_productCollection->getAllIds());
                // print_r($productUpdatedIDs);
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                /** @var \Magento\Catalog\Model\ResourceModel\Product\Collection $productCollection */
                $productDataCollection = $objectManager->create('Magento\Catalog\Model\ResourceModel\Product\Collection');
                /** Apply filters here */
                $prodDatacollection = $productDataCollection->addAttributeToSelect('*');
                $prodDatacollection->addAttributeToFilter(
                    'collection_id',array("eq"=>$collectionlist->getSqlServId())
                )
                ->addAttributeToFilter(
                    'platform_id',array("eq"=>$platformlist->getSqlServId())
                )
                ->addFieldToFilter('entity_id', array('in' => $productUpdatedIDs))
                ->setOrder('product_sort_order','ASC')
                            ->load();

                if(count($prodDatacollection) < 1){
                    continue;
                }

                $attributeList = ['beam_spread_option','housing_type_filter','dimming_filter','maximum_delivered_lumens_filter','minimum_delivered_lumens_filter'];
                
                // foreach( $attributeList as $attributeCode){

                //     //Get product attribute Labels
                //     $attr = $_product->getResource()->getAttribute($attributeCode);
                //     if ($attr->usesSource()) {
                //         $optionText = $attr->getSource()->getOptionText($optionId);
                //     }

                // }

                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                /* Create a new product object */
                $attributeRepository = $objectManager->create('\Magento\Eav\Api\AttributeRepositoryInterface');
                $attribute = $attributeRepository->get('4', 'beam_spread_option');
                $value = $attribute->getSource()->getOptionText(87075);
               //print_r($attribute->getFrontend()->getLabel());
                //exit('coming here');

                //print_r($value);
                //exit('coming here');

                // Get a request object singleton
                //$request = $objectManager->get(\Magento\Framework\App\RequestInterface::class);


             
                $specification = [];
                foreach( $attributeList as $attributeCode){    
                    $collectionValue = $prodDatacollection->getColumnValues($attributeCode);
                    $secondColl = [];
                     if(strlen(implode($collectionValue)) != 0){
                        if($attributeCode == 'housing_type_filter'){
                            echo '<pre>housing type';
                            print_r($collectionValue);
                            echo '</pre>';
                            $splitValue = [];
                            foreach($collectionValue as $listItem){
                                echo '<pre>inside foreach ';
                                print_r($listItem);
                               
                               $splitValue =  explode(',',$listItem); 
                               $secondColl = ;
                               //$splitValue =  $listItem; 
                              
                               array_push($collectionValue,$splitValue);
                               print_r($collectionValue);
                               echo 'outside type</pre>';
                            }
                            
                            echo '<pre>after housing type';
                            //array_unique($collectionValue);
                            print_r($collectionValue);
                            echo '</pre>';
                        }
                        $collectionValue = array_unique($collectionValue);
                        $specification[$attributeCode] = $block->getAttributeOptionLabels($attributeCode, $collectionValue);
                     }
                    
                } 

                
                $housing = $prodDatacollection->getColumnValues('housing_type_filter');
                $dimming = $prodDatacollection->getColumnValues('dimming_filter');
                $deliveredLumenMax = $prodDatacollection->getColumnValues('maximum_delivered_lumens_filter');
                $deliveredLumenMin = $prodDatacollection->getColumnValues('minimum_delivered_lumens_filter');
                
                //array_unique($beamSpreadOption);

                echo '<pre>1';
                print_r($housing);
                print_r($specification);
                if(isset($specification['beam_spread_option'])){
                    print_r($specification['beam_spread_option']);
                }
                
                echo '</pre>';
                /*
                print_r($housing);
                echo (strlen(implode($housing)) == 0) ? 'Empty' : 'Not Empty';
                print_r($dimming);
                echo (strlen(implode($dimming)) == 0) ? 'Empty' : 'Not Empty';
                print_r($deliveredLumenMax);
                echo (strlen(implode($deliveredLumenMax)) == 0) ? 'Empty' : 'Not Empty';
                print_r($deliveredLumenMin);
                echo (strlen(implode($deliveredLumenMin)) == 0) ? 'Empty' : 'Not Empty';
                echo '</pre>';
                */

                //echo '<pre>';
               // print_r($columnValues);
                //print_r($prodDatacollection->getData());
                //exit('coming here');


            ?>
                <div class="item product product-item">
                    <div class="product-item-info">
                        <a href="javascript:void(0);" class="product photo product-item-photo">
                            <img src="<?= $this->getViewFileUrl('Magento_Catalog::images/placeholder.png') ?>" width="240" height="300" />
                        </a>
                        <div class="d-flex product-item-thumb">
                            <a href="javascript:void(0);">
                                <img src="<?= $this->getViewFileUrl('Magento_Catalog::images/placeholder.png') ?>" width="50" height="50" />
                            </a>
                            <a href="javascript:void(0);">
                                <img src="<?= $this->getViewFileUrl('Magento_Catalog::images/placeholder.png') ?>" width="50" height="50" />
                            </a>
                            <a href="javascript:void(0);">
                                <img src="<?= $this->getViewFileUrl('Magento_Catalog::images/placeholder.png') ?>" width="50" height="50" />
                            </a>
                            <a href="javascript:void(0);">
                                <img src="<?= $this->getViewFileUrl('Magento_Catalog::images/placeholder.png') ?>" width="50" height="50" />
                            </a>
                            <a href="javascript:void(0);">
                                <img src="<?= $this->getViewFileUrl('Magento_Catalog::images/placeholder.png') ?>" width="50" height="50" />
                            </a>
                        </div>
                        <div class="product details product-item-details">
                            <div class="product name product-item-name">
                                <a class="product-item-link" href="javascript:void(0);">
                                    <?= $platformlist->getWebName(); ?>
                                </a>
                            </div>
                            <div class="product-attribute-head">Specifications</div>

                            <?php 
                            /*
                            foreach($specification as $key => $item){
                            ?>
                             <div class="spec-inline">
                                <ul class="product-attribute-list">
                                    <span><?php echo $key ?>:</span>
                                    <!--<li>850 - 1500</li>-->
                                    <li><?php print_r($item,true); ?></li>
                                </ul>
                            </div>
                            <?php
                            }
                            */
                            ?>
                            <?php 
                            if(!empty($specification['minimum_delivered_lumens_filter']) || !empty($specification['maximum_delivered_lumens_filter']) ){             
                            ?>
                            <div class="spec-inline">
                                <ul class="product-attribute-list">
                                    <span>Delivered Lumens:</span>
                                    <!--<li>850 - 1500</li>-->
                                    <li><?php echo implode(',',$specification['minimum_delivered_lumens_filter']).' - '.implode(',',$specification['maximum_delivered_lumens_filter']); ?></li>
                                </ul>
                            </div>

                            <?php } ?>

                            <?php 
                            if(!empty($specification['binning']) ){             
                            ?>
                            <div class="spec-inline">
                                <ul class="product-attribute-list">
                                    <span>Binning:</span>
                                   <!-- <li>1-Step,</li>
                                    <li>2-Step</li> -->
                                    <li><?php echo implode(',',$specification['binning']) ?></li>
                                </ul>
                            </div>
                            <?php } ?>


                            <?php 
                            if(!empty($specification['beam_spread_option']) ){             
                            ?>
                            <div class="spec-inline">
                                <ul class="product-attribute-list">
                                    <span>Beam Spread:</span>
                                    <!--<li>20° - 60°,</li>
                                    <li>Wall Wash</li>-->
                                    <li><?php //echo implode(',',$specification['beam_spread_option']) ?></li>
                                </ul>
                            </div>
                            <?php } ?>

                            <?php 
                            if(!empty($specification['housing_type_filter']) ){             
                            ?>
                            <div class="spec-inline">
                                <ul class="product-attribute-list">
                                    <span>Housings:</span>
                                    <!--<li>IC,</li>
                                    <li>Non-IC,</li>
                                    <li>Chicago Plenum</li>-->
                                    <li><?php //echo implode(',',$housing)?> </li>
                                </ul>
                            </div>
                            <?php } ?>


                            <?php 
                            if(!empty($specification['dimming']) ){             
                            ?>
                            <div class="spec-inline">
                                <ul class="product-attribute-list">
                                    <span>Dimming:</span>
                                    <!--<li>Phase/Triac,</li>
                                    <li>0-10V,</li>
                                    <li>DALI</li>-->
                                    <li><?php //echo implode(',',$specification['housing_type_filter']); ?></li>
                                </ul>
                            </div>
                            <?php } ?>

                            <?php 
                            if(!empty($specification['rating_certification']) ){             
                            ?>
                            <div class="spec-inline">
                                <ul class="product-attribute-list">
                                    <span>Ratings/Certification:</span>
                                    <!--<li>T24,</li>
                                    <li>Wet,</li>
                                    <li>Sauna/Steam,</li>
                                    <li>IC Spray Foam</li>-->
                                    <li><?php ?> </li>
                                </ul>
                            </div>
                            <?php } ?>

                            <div class="product-attribute-head">Products</div>
                            <div class="tech-attributes">
                                <ul class="product-attribute-list">
                                <?php 
                                        // echo '<pre>';
                                            // print_r($_productCollection->getData());
                                            //$_productCollection->addAttributeToSelect('collection_id','platform_id');
                                            //echo get_class($_productCollection);
                                            //print_r($_productCollection->getData());
                                            //exit(' coming here');
                                            // $_productCollection->getSelect()->reset(\Magento\Framework\DB\Select::WHERE);

                                            //$select= $_productCollection->getSelectCountSql();

                                            //$select
                                            //    ->from('newsletter_subscriber', array('some_column'))
                                            //    ->distinct();

                                            //$select->addAttributeToSelect('collection_id','platform_id');
                                            /*
                                            $select->addAttributeToFilter(
                                                'collection_id',array("eq"=>$collectionlist->getSqlServId())
                                            );
                                            $select->addAttributeToFilter(
                                                'platform_id',array("eq"=>$platformlist->getSqlServId())
                                            );
                                            //$_productCollection->load();
                                            echo $select->getSelect();
                                            
                                            echo ' || Collection ID:- '.$collectionlist->getSqlServId()." || Platform ID:- ".$platformlist->getSqlServId()." ||";

                                            echo " after".count($select);*/
                                            //echo count($prodDatacollection); exit('coming here');
                                    foreach($prodDatacollection as $item) {

                                        //var_dump($item);
                                    // echo ' platform id'; print_r($item->getName());
                                ?>
                                    <li><a href="javascript:void(0);"><?= $item->getName(); ?></a></li>
                                <?php } //exit(' exit');//foreach classe for produdct item ?>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            <?php  } ?>
        </div>
    <?php  } ?>
</div>


<?php /*
<script>
    require([
        'jquery',
        'owlcarousel'
    ],function($) {
        $(document).ready(function(){
            $('.product-item-thumb').owlCarousel({
                nav : true,
                dots: false,
                autoPlay: false,
                margin: 10,
                items : 5
            });
        });
    })
</script>
*/ ?>