<?php
/**
 * Lyonscg_RequisitionList
 *
 * @category  Lyons
 * @package   Lyonscg_RequisitionList
 * @author    Tetiana Mamchik<tanya.mamchik@capgemini.com>
 * @copyright Copyright (c) 2020 Lyons Consulting Group (www.lyonscg.com)
 */

/**
 * @var $block \Magento\RequisitionList\Block\Requisition\View\Details
 */
?>
<div class="block-requisition-management">
    <?= $block->getChildHtml('requisition.list.title') ?>

    <?php if ($block->getParentBlock()->getItemErrorCount()) : ?>
        <div class="message error">
            <span>
                <?= (int) $block->getParentBlock()->getItemErrorCount() ?>
                <?= $block->escapeHtml(__('product(s) require your attention')) ?>
            </span>
        </div>
    <?php endif ?>

    <?php if ($block->getItemCount()) : ?>
        <?= $block->getChildHtml('toolbar') ?>
    <?php endif ?>
</div>
